-- taxonomy refactor: phase 1, seed kinds.
--
-- inserts the built-in `taxon_kindz` rows. ids are auto-generated by
-- the column default; downstream sql / rust code looks kinds up by
-- `slug`, never by id.
--
-- value_type:
--   'categorical' = has rows in `taxonz` (genre, mood, instrument, era, key, location, label)
--   'scalar_f64'  = no taxonz rows; values land in `scalar_attributez` (bpm, loudness_db, energy)
--
-- colors are the existing palette tokens where available (genre keeps
-- its current indigo). new kinds use neutral palette slots; ui can
-- override at any time by updating the row.

INSERT INTO taxon_kindz (slug, label, description, color, value_type, unit, display_order, is_user_defined) VALUES
  ('genre',       'genre',       'musical genre (rock, jazz, techno, ...)',                            '#6366f1', 'categorical', NULL,  10, 0),
  ('mood',        'mood',        'overall feel (mellow, aggressive, melancholic, ...)',                '#a855f7', 'categorical', NULL,  20, 0),
  ('instrument',  'instrument',  'prominent instrumentation (piano, guitar, synth, ...)',              '#06b6d4', 'categorical', NULL,  30, 0),
  ('era',         'era',         'time period or scene (90s, post-2000, no-wave, ...)',                '#f59e0b', 'categorical', NULL,  40, 0),
  ('key',         'key',         'musical key (c-major, a-minor, f#-minor, ...)',                      '#ec4899', 'categorical', NULL,  50, 0),
  ('location',    'location',    'geographic origin (london uk, detroit mi, berlin, ...)',             '#10b981', 'categorical', NULL,  60, 0),
  ('label',       'label',       'record label (warp records, blue note, sub pop, ...)',               '#64748b', 'categorical', NULL,  70, 0),
  ('bpm',         'bpm',         'tempo in beats per minute',                                          '#ef4444', 'scalar_f64',  'bpm', 80, 0),
  ('loudness_db', 'loudness',    'integrated loudness in decibels (typically -30..0)',                 '#f97316', 'scalar_f64',  'db',  90, 0),
  ('energy',      'energy',      'normalized energy score 0..1 (low = ambient, high = intense)',       '#84cc16', 'scalar_f64',  NULL, 100, 0);
