//! User service for business logic and coordination
//!
//! This module provides high-level user services that handle business logic,
//! validation, and coordination between different components of the user system.

use crate::users::models::*;
use crate::users::repository::UserRepository;
use crate::wordlist::{generate_word_code, initialize_wordlist, ManagementWordlistConfig};

/// Service for user-related business operations
pub struct UserService {
    repository: UserRepository,
}

impl UserService {
    /// Create a new user service instance
    pub fn new() -> Self {
        Self {
            repository: UserRepository::new(),
        }
    }

    /// Create a new user service with custom repository
    pub fn with_repository(repository: UserRepository) -> Self {
        Self { repository }
    }

    /// Register a new user with optional invite code validation
    pub async fn register_user(&self, request: &CreateUserRequest) -> AuthResult<User> {
        // Validate username
        self.validate_username(&request.username)?;

        // Check if username already exists
        if let Some(_existing) = self
            .repository
            .find_user_by_username(&request.username)
            .await?
        {
            return Err(AuthError::UserAlreadyExists {
                username: request.username.clone(),
            });
        }

        // Validate invite code if provided
        if let Some(invite_code) = &request.invite_code {
            self.validate_invite_code(invite_code).await?;
        }

        // Create the user
        let user = self.repository.create_user(request).await?;

        // Mark invite code as used if provided
        if let Some(invite_code) = &request.invite_code {
            self.repository
                .use_invite_code(invite_code, &user.id)
                .await?;
        }

        Ok(user)
    }

    /// Get user by ID
    pub async fn get_user(&self, user_id: &str) -> AuthResult<User> {
        self.repository
            .find_user_by_id(user_id)
            .await?
            .ok_or(AuthError::UserNotFound)
    }

    /// Get user by username
    pub async fn get_user_by_username(&self, username: &str) -> AuthResult<User> {
        self.repository
            .find_user_by_username(username)
            .await?
            .ok_or(AuthError::UserNotFoundByUsername {
                username: username.to_string(),
            })
    }

    /// Update user account
    pub async fn update_user(
        &self,
        user_id: &str,
        request: &UpdateUserRequest,
        requesting_user: &User,
    ) -> AuthResult<User> {
        // Check permissions - only admins can change roles, users can update themselves
        if request.role.is_some() && !requesting_user.can_manage_users() {
            return Err(AuthError::InsufficientPermissions);
        }

        // Ensure user exists
        let _existing_user = self.get_user(user_id).await?;

        self.repository.update_user(user_id, request).await
    }

    /// Delete user account (soft delete)
    pub async fn delete_user(&self, user_id: &str, requesting_user: &User) -> AuthResult<()> {
        // Only admins can delete users, or users can delete themselves
        if user_id != requesting_user.id && !requesting_user.can_manage_users() {
            return Err(AuthError::InsufficientPermissions);
        }

        self.repository.delete_user(user_id).await
    }

    /// List users with pagination and filtering
    pub async fn list_users(
        &self,
        params: &UserQueryParams,
        requesting_user: &User,
    ) -> AuthResult<Vec<User>> {
        // Only admins can list all users
        if !requesting_user.can_manage_users() {
            return Err(AuthError::InsufficientPermissions);
        }

        self.repository.list_users(params).await
    }

    /// Generate and create invite codes
    pub async fn generate_invite_codes(
        &self,
        request: &CreateInviteCodeRequest,
        count: u32,
        word_count: usize,
        requesting_user: &User,
    ) -> AuthResult<Vec<InviteCode>> {
        // Only admins can create invite codes
        if !requesting_user.can_manage_invites() {
            return Err(AuthError::InsufficientPermissions);
        }

        let mut invite_codes = Vec::new();

        for _ in 0..count {
            // Generate word-based code
            let code =
                generate_word_code(word_count).map_err(|e| AuthError::Config(e.to_string()))?;

            // Create invite code record
            let mut create_request = request.clone();
            let invite_code = InviteCode {
                id: String::new(), // Will be generated by database
                code,
                created_at: 0, // Will be set by database
                used_at: None,
                used_by_id: None,
                is_active: true,
                code_type: create_request.code_type.unwrap_or_default(),
                link_for_user_id: create_request.link_for_user_id,
                link_expires_at: create_request.expires_hours.map(|hours| {
                    time::OffsetDateTime::now_utc().unix_timestamp() + (hours as i64 * 3600)
                }),
            };

            // This would normally create in database, but using placeholder for now
            // let created_invite = self.repository.create_invite_code(&create_request).await?;
            // invite_codes.push(created_invite);

            // TODO: Remove this placeholder when repository is implemented
            invite_codes.push(invite_code);
        }

        Ok(invite_codes)
    }

    /// Validate an invite code
    pub async fn validate_invite_code(&self, code: &str) -> AuthResult<InviteCode> {
        let invite_code = self
            .repository
            .find_invite_code(code)
            .await?
            .ok_or_else(|| AuthError::InviteCodeNotFound {
                code: code.to_string(),
            })?;

        if !invite_code.is_valid_for_use() {
            if invite_code.used_at.is_some() {
                return Err(AuthError::InviteCodeAlreadyUsed);
            }
            if invite_code.is_expired() {
                return Err(AuthError::InviteCodeExpired);
            }
            return Err(AuthError::InvalidInviteCode);
        }

        Ok(invite_code)
    }

    /// List invite codes
    pub async fn list_invite_codes(
        &self,
        active_only: bool,
        requesting_user: &User,
    ) -> AuthResult<Vec<InviteCode>> {
        // Only admins can list invite codes
        if !requesting_user.can_manage_invites() {
            return Err(AuthError::InsufficientPermissions);
        }

        self.repository.list_invite_codes(active_only).await
    }

    /// Deactivate an invite code
    pub async fn deactivate_invite_code(
        &self,
        code: &str,
        requesting_user: &User,
    ) -> AuthResult<()> {
        // Only admins can deactivate invite codes
        if !requesting_user.can_manage_invites() {
            return Err(AuthError::InsufficientPermissions);
        }

        self.repository.deactivate_invite_code(code).await
    }

    /// Validate username format and constraints
    fn validate_username(&self, username: &str) -> AuthResult<()> {
        if username.is_empty() {
            return Err(AuthError::InvalidUsername {
                reason: "Username cannot be empty".to_string(),
            });
        }

        if username.len() < 2 {
            return Err(AuthError::InvalidUsername {
                reason: "Username must be at least 2 characters".to_string(),
            });
        }

        if username.len() > 50 {
            return Err(AuthError::InvalidUsername {
                reason: "Username must be less than 50 characters".to_string(),
            });
        }

        // Check for valid characters (alphanumeric, underscore, hyphen)
        if !username
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '-')
        {
            return Err(AuthError::InvalidUsername {
                reason: "Username can only contain letters, numbers, underscore, and hyphen"
                    .to_string(),
            });
        }

        // Don't allow usernames that start or end with special characters
        if username.starts_with('_') || username.starts_with('-') {
            return Err(AuthError::InvalidUsername {
                reason: "Username cannot start with underscore or hyphen".to_string(),
            });
        }

        if username.ends_with('_') || username.ends_with('-') {
            return Err(AuthError::InvalidUsername {
                reason: "Username cannot end with underscore or hyphen".to_string(),
            });
        }

        Ok(())
    }
}

impl Default for UserService {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_service_creation() {
        let service = UserService::new();
        // Basic smoke test that service can be created
    }

    #[test]
    fn test_username_validation() {
        let service = UserService::new();

        // Valid usernames
        assert!(service.validate_username("user123").is_ok());
        assert!(service.validate_username("test_user").is_ok());
        assert!(service.validate_username("user-name").is_ok());

        // Invalid usernames
        assert!(service.validate_username("").is_err());
        assert!(service.validate_username("a").is_err());
        assert!(service.validate_username("_user").is_err());
        assert!(service.validate_username("user_").is_err());
        assert!(service.validate_username("-user").is_err());
        assert!(service.validate_username("user-").is_err());
        assert!(service.validate_username("user@name").is_err());
        assert!(service.validate_username(&"a".repeat(51)).is_err());
    }
}
