import type { WalkNode } from "../types";
import { artist, album, ghostArtist } from "./factories";

export const LOCAL_ARTISTS: WalkNode[] = [
  artist("local", "a01", "Grouper", 3),
  artist("local", "a02", "Demdike Stare", 4),
  artist("local", "a03", "Arca", 5),
  artist("local", "a04", "The Body", 4),
  artist("local", "a05", "Kamasi Washington", 3),
  artist("local", "a06", "Pharoah Sanders", 4),
  artist("local", "a07", "Wire", 5),
  artist("local", "a08", "Gang of Four", 3),
  artist("local", "a09", "Swans", 6),
  artist("local", "a10", "Sunn O)))", 3),
  artist("local", "a11", "Actress", 4),
  artist("local", "a12", "Burial", 2),
  artist("local", "a13", "Low", 4),
  artist("local", "a14", "Godspeed You! Black Emperor", 3),
  artist("local", "a15", "Explosions in the Sky", 3),
  artist("local", "a16", "Tim Hecker", 4),
  artist("local", "a17", "Stars of the Lid", 2),
  artist("local", "a18", "William Basinski", 3),
  artist("local", "a19", "Oval", 2),
  artist("local", "a20", "Autechre", 5),
  artist("local", "a21", "Aphex Twin", 6),
  artist("local", "a22", "Boards of Canada", 4),
  artist("local", "a23", "Massive Attack", 4),
  artist("local", "a24", "Portishead", 3),
  artist("local", "a25", "Tricky", 3),
  artist("local", "a26", "Flying Lotus", 4),
  artist("local", "a27", "Kendrick Lamar", 5),
  artist("local", "a28", "Madlib", 4),
  artist("local", "a29", "MF DOOM", 3),
  artist("local", "a30", "The Bug", 3),
  artist("local", "a31", "Coil", 5),
  artist("local", "a32", "Current 93", 4),
  artist("local", "a33", "Death in June", 3),
  artist("local", "a34", "Einstürzende Neubauten", 4),
  artist("local", "a35", "Throbbing Gristle", 3),
  artist("local", "a36", "Cabaret Voltaire", 3),
  artist("local", "a37", "This Heat", 2),
  artist("local", "a38", "Pan Sonic", 3),
  artist("local", "a39", "Merzbow", 4),
  artist("local", "a40", "Dead Can Dance", 3),
  artist("local", "a41", "4AD Sampler", 2),
  artist("local", "a42", "Cocteau Twins", 4),
  artist("local", "a43", "The Cure", 5),
  artist("local", "a44", "Joy Division", 3),
  artist("local", "a45", "Bauhaus", 3),
  artist("local", "a46", "Siouxsie and the Banshees", 4),
  artist("local", "a47", "The Slits", 2),
  artist("local", "a48", "Public Image Ltd", 3),
  artist("local", "a49", "Can", 4),
  artist("local", "a50", "Faust", 3),
  artist("local", "a51", "Neu!", 2),
  artist("local", "a52", "Cluster", 2),
  artist("local", "a53", "Harmonia", 2),
  artist("local", "a54", "Miles Davis", 5),
  artist("local", "a55", "John Coltrane", 5),
  artist("local", "a56", "Alice Coltrane", 3),
  artist("local", "a57", "Sun Ra", 4),
  artist("local", "a58", "Albert Ayler", 3),
  artist("local", "a59", "Ornette Coleman", 4),
  artist("local", "a60", "Charles Mingus", 4),
  artist("local", "a61", "Four Tet", 3),
  artist("local", "a62", "Squarepusher", 3),
  artist("local", "a63", "Bibio", 2),
  artist("local", "a64", "Mount Kimbie", 2),
  artist("local", "a65", "Jon Hopkins", 3),
  artist("local", "a66", "Andy Stott", 3),
  artist("local", "a67", "Raime", 2),
  artist("local", "a68", "Objekt", 2),
  artist("local", "a69", "Floating Points", 3),
  artist("local", "a70", "Lone", 2),
  artist("local", "a71", "Bonobo", 3),
  artist("local", "a72", "Jamie xx", 2),
  artist("local", "a73", "James Blake", 3),
  artist("local", "a74", "FKA Twigs", 2),
  artist("local", "a75", "Kelela", 2),
  artist("local", "a76", "Laurel Halo", 3),
  artist("local", "a77", "Holly Herndon", 2),
  artist("local", "a78", "J Dilla", 3),
  artist("local", "a79", "JPEGMAFIA", 3),
  artist("local", "a80", "billy woods", 3),
  artist("local", "a81", "Armand Hammer", 2),
  artist("local", "a82", "Quelle Chris", 2),
  artist("local", "a83", "Moor Mother", 3),
  artist("local", "a84", "Open Mike Eagle", 2),
  artist("local", "a85", "Dry Cleaning", 2),
  artist("local", "a86", "black midi", 3),
  artist("local", "a87", "Squid", 2),
  artist("local", "a88", "Shame", 3),
  artist("local", "a89", "Idles", 3),
  artist("local", "a90", "Fontaines D.C.", 3),
  artist("local", "a91", "Shabaka Hutchings", 3),
  artist("local", "a92", "Nubya Garcia", 2),
  artist("local", "a93", "Makaya McCraven", 3),
  artist("local", "a94", "Irreversible Entanglements", 2),
  artist("local", "a95", "Moses Sumney", 2),
];

export const LOCAL_ALBUMS: WalkNode[] = [
  album("local", "lp01", "Dragging a Dead Deer"),
  album("local", "lp02", "A I A: Alien Observer"),
  album("local", "lp03", "Grid of Points"),
  album("local", "lp04", "Moan"),
  album("local", "lp05", "Testpressing #8"),
  album("local", "lp06", "Obwo"),
  album("local", "lp07", "Mutant"),
  album("local", "lp08", "Xen"),
  album("local", "lp09", "Kick II"),
  album("local", "lp10", "No One Deserves Happiness"),
  album("local", "lp11", "I've Seen All I Need to See"),
  album("local", "lp12", "The Witness"),
  album("local", "lp13", "Pharoah"),
  album("local", "lp14", "Live in Paris"),
  album("local", "lp15", "Pink Flag"),
  album("local", "lp16", "154"),
  album("local", "lp17", "Chairs Missing"),
  album("local", "lp18", "Entertainment!"),
  album("local", "lp19", "Solid Gold"),
  album("local", "lp20", "The Great Annihilator"),
  album("local", "lp21", "Cop"),
  album("local", "lp22", "To Be Kind"),
  album("local", "lp23", "White 1"),
  album("local", "lp24", "Flight"),
  album("local", "lp25", "Ghettoville"),
  album("local", "lp26", "Untrue"),
  album("local", "lp27", "Luminous Spaces"),
  album("local", "lp28", "Things We Lost in the Fire"),
  album("local", "lp29", "Lift Your Skinny Fists"),
  album("local", "lp30", "F♯ A♯ ∞"),
  album("local", "lp31", "The Earth Is Not a Cold Dead Place"),
  album("local", "lp32", "Those Who Tell the Truth"),
  album("local", "lp33", "Ravedeath, 1972"),
  album("local", "lp34", "Virgins"),
  album("local", "lp35", "Konoyo"),
  album("local", "lp36", "And Their Refinement of the Decline"),
  album("local", "lp37", "The Disintegration Loops"),
  album("local", "lp38", "Melancholia"),
  album("local", "lp39", "Systemisch"),
  album("local", "lp40", "Tri Repetae"),
  album("local", "lp41", "Untilted"),
  album("local", "lp42", "Richard D. James Album"),
  album("local", "lp43", "Drukqs"),
  album("local", "lp44", "Music Has the Right to Children"),
  album("local", "lp45", "Geogaddi"),
  album("local", "lp46", "Mezzanine"),
  album("local", "lp47", "Dummy"),
  album("local", "lp48", "Maxinquaye"),
  album("local", "lp49", "You're Dead!"),
  album("local", "lp50", "Until the Quiet Comes"),
  album("local", "lp51", "To Pimp a Butterfly"),
  album("local", "lp52", "DAMN."),
  album("local", "lp53", "Madvillainy"),
  album("local", "lp54", "Mm..Food"),
  album("local", "lp55", "Venomous Villain"),
  album("local", "lp56", "London Zoo"),
  album("local", "lp57", "Microscopic Sound"),
  album("local", "lp58", "Scorn"),
  album("local", "lp59", "Abora"),
  album("local", "lp60", "Nun"),
  album("local", "lp61", "Unclean"),
  album("local", "lp62", "Auto-da-Fé"),
  album("local", "lp63", "Current 93 Presents"),
  album("local", "lp64", "Nada!"),
  album("local", "lp65", "Strategies Against Architecture"),
  album("local", "lp66", "Second Annual Report"),
  album("local", "lp67", "Mix-Up"),
  album("local", "lp68", "Deceit"),
  album("local", "lp69", "EP/A1 Sides"),
  album("local", "lp70", "Pulse Demon"),
  album("local", "lp71", "Dead Can Dance"),
  album("local", "lp72", "Within the Realm of a Dying Sun"),
  album("local", "lp73", "Heaven or Las Vegas"),
  album("local", "lp74", "Blue Bell Knoll"),
  album("local", "lp75", "Pornography"),
  album("local", "lp76", "Disintegration"),
  album("local", "lp77", "Unknown Pleasures"),
  album("local", "lp78", "Closer"),
  album("local", "lp79", "In the Flat Field"),
  album("local", "lp80", "Kaleidoscope"),
  album("local", "lp81", "The Scream"),
  album("local", "lp82", "Metal Box"),
  album("local", "lp83", "Tago Mago"),
  album("local", "lp84", "Ege Bamyasi"),
  album("local", "lp85", "Faust IV"),
  album("local", "lp86", "Neu! 2"),
  album("local", "lp87", "Zuckerzeit"),
  album("local", "lp88", "Musik von Harmonia"),
  album("local", "lp89", "Bitches Brew"),
  album("local", "lp90", "Kind of Blue"),
  album("local", "lp91", "A Love Supreme"),
  album("local", "lp92", "Interstellar Space"),
  album("local", "lp93", "World Galaxy"),
  album("local", "lp94", "Spiritual Unity"),
  album("local", "lp95", "Bells"),
  album("local", "lp96", "The Shape of Jazz to Come"),
  album("local", "lp97", "The Black Saint and the Sinner Lady"),
  album("local", "lp98", "Let My Children Hear Music"),
  album("local", "lp99",  "Rounds"),
  album("local", "lp100", "There Is Love in You"),
  album("local", "lp101", "Sixteen Oceans"),
  album("local", "lp102", "Hard Normal Daddy"),
  album("local", "lp103", "Ultravisitor"),
  album("local", "lp104", "Feed Me Weird Things"),
  album("local", "lp105", "Ambivalence Avenue"),
  album("local", "lp106", "Silver Wilkinson"),
  album("local", "lp107", "Crooks & Lovers"),
  album("local", "lp108", "Love What Survives"),
  album("local", "lp109", "Immunity"),
  album("local", "lp110", "Singularity"),
  album("local", "lp111", "Piano Versions"),
  album("local", "lp112", "Luxury Problems"),
  album("local", "lp113", "Faith in Strangers"),
  album("local", "lp114", "Too Many Voices"),
  album("local", "lp115", "Quarter Turns"),
  album("local", "lp116", "Tooth"),
  album("local", "lp117", "Flatland"),
  album("local", "lp118", "Needle & Thread"),
  album("local", "lp119", "Elaenia"),
  album("local", "lp120", "Crush"),
  album("local", "lp121", "Promises"),
  album("local", "lp122", "Galaxy Garden"),
  album("local", "lp123", "Reality Testing"),
  album("local", "lp124", "Black Sands"),
  album("local", "lp125", "The North Borders"),
  album("local", "lp126", "Migration"),
  album("local", "lp127", "In Colour"),
  album("local", "lp128", "In Waves"),
  album("local", "lp129", "James Blake"),
  album("local", "lp130", "Overgrown"),
  album("local", "lp131", "The Colour in Anything"),
  album("local", "lp132", "LP1"),
  album("local", "lp133", "Magdalene"),
  album("local", "lp134", "Take Me Apart"),
  album("local", "lp135", "Raven"),
  album("local", "lp136", "Quarantine"),
  album("local", "lp137", "Dust"),
  album("local", "lp138", "Atlas"),
  album("local", "lp139", "Platform"),
  album("local", "lp140", "Proto"),
  album("local", "lp141", "Donuts"),
  album("local", "lp142", "The Shining"),
  album("local", "lp143", "Welcome 2 Detroit"),
  album("local", "lp144", "Veteran"),
  album("local", "lp145", "All My Heroes Are Cornballs"),
  album("local", "lp146", "LP!"),
  album("local", "lp147", "Hiding Places"),
  album("local", "lp148", "Maps"),
  album("local", "lp149", "Church"),
  album("local", "lp150", "Shrines"),
  album("local", "lp151", "Haram"),
  album("local", "lp152", "Guns"),
  album("local", "lp153", "Innocent Country 2"),
  album("local", "lp154", "Fetish Bones"),
  album("local", "lp155", "Brass"),
  album("local", "lp156", "Black Encyclopedia of the Air"),
  album("local", "lp157", "Brick Body Kids Still Daydream"),
  album("local", "lp158", "Anime, Trauma and Divorce"),
  album("local", "lp159", "New Long Leg"),
  album("local", "lp160", "Stumpwork"),
  album("local", "lp161", "Schlagenheim"),
  album("local", "lp162", "Cavalcade"),
  album("local", "lp163", "Hellfire"),
  album("local", "lp164", "Bright Green Field"),
  album("local", "lp165", "O Monolith"),
  album("local", "lp166", "Songs of Praise"),
  album("local", "lp167", "Drunk Tank Pink"),
  album("local", "lp168", "Food for Worms"),
  album("local", "lp169", "Joy as an Act of Resistance"),
  album("local", "lp170", "Ultra Mono"),
  album("local", "lp171", "Crawler"),
  album("local", "lp172", "Dogrel"),
  album("local", "lp173", "A Hero's Death"),
  album("local", "lp174", "Skinty Fia"),
  album("local", "lp175", "Wisdom of Elders"),
  album("local", "lp176", "We Are Sent Here by History"),
  album("local", "lp177", "To Wisdom the Prize"),
  album("local", "lp178", "Source"),
  album("local", "lp179", "Source (We Move)"),
  album("local", "lp180", "Universal Beings"),
  album("local", "lp181", "In These Times"),
  album("local", "lp182", "Deciphering the Message"),
  album("local", "lp183", "Irreversible Entanglements"),
  album("local", "lp184", "Open the Gates"),
  album("local", "lp185", "Aromanticism"),
  album("local", "lp186", "Græ"),
];

export const LOCAL_GHOSTS: WalkNode[] = [
  ghostArtist("g01", "Liz Harris"),
  ghostArtist("g02", "Drew McDowall"),
  ghostArtist("g03", "Mick Harris"),
  ghostArtist("g04", "Lawrence English"),
  ghostArtist("g05", "Carla Bozulich"),
  ghostArtist("g06", "Stephen O'Malley"),
];
