export const LOCAL_RELATIONS: [string, string, number][] = [
  ["genres", "genres", 100],
  ["tags", "tags", 8],
  ["favorites", "favorites", 14],
  ["recent_albums", "recent albums", 12],
  ["era", "era", 5],
  ["mood", "mood", 8],
  ["collaborators", "collaborators", 6],
];

export const LOCAL_GENRES: [string, string, number][] = [
  ["ambient",        "ambient",           14],
  ["post_punk",      "post-punk",          9],
  ["jazz",           "jazz",              12],
  ["noise",          "noise",              7],
  ["drone",          "drone",              6],
  ["shoegaze",       "shoegaze",           8],
  ["dark_wave",      "dark wave",          5],
  ["industrial",     "industrial",        10],
  ["folk",           "folk",              11],
  ["hip_hop",        "hip-hop",           13],
  ["electronic",     "electronic",        18],
  ["experimental",   "experimental",      16],
  ["post_rock",      "post-rock",          7],
  ["krautrock",      "krautrock",          4],
  ["psychedelic",    "psychedelic",        9],
  ["black_metal",    "black metal",        6],
  ["doom_metal",     "doom metal",         5],
  ["slowcore",       "slowcore",           4],
  ["rnb",            "r&b",               11],
  ["soul",           "soul",              10],
  ["funk",           "funk",               8],
  ["reggae",         "reggae",             5],
  ["dub",            "dub",                6],
  ["techno",         "techno",            12],
  ["house",          "house",             10],
  ["trance",         "trance",             4],
  ["breakbeat",      "breakbeat",          5],
  ["jungle",         "jungle",             4],
  ["garage",         "garage",             6],
  ["grime",          "grime",              5],
  ["uk_bass",        "UK bass",            4],
  ["footwork",       "footwork",           3],
  ["deconstructed",  "deconstructed",      5],
  ["new_age",        "new age",            4],
  ["minimalism",     "minimalism",         6],
  ["musique_concrete","musique concrète",  4],
  ["noise_rock",     "noise rock",         6],
  ["math_rock",      "math rock",          5],
  ["emo",            "emo",                4],
  ["hardcore",       "hardcore",           7],
  ["punk",           "punk",               8],
  ["grunge",         "grunge",             5],
  ["indie_rock",     "indie rock",         9],
  ["dream_pop",      "dream pop",          8],
  ["chamber_pop",    "chamber pop",        4],
  ["baroque_pop",    "baroque pop",        3],
  ["art_rock",       "art rock",           6],
  ["glam",           "glam",               4],
  ["progressive",    "progressive",        7],
  ["fusion",         "fusion",             5],
  ["free_jazz",      "free jazz",          5],
  ["bebop",          "bebop",              4],
  ["cool_jazz",      "cool jazz",          3],
  ["modal_jazz",     "modal jazz",         4],
  ["latin_jazz",     "latin jazz",         3],
  ["afrobeat",       "afrobeat",           5],
  ["worldbeat",      "worldbeat",          4],
  ["cumbia",         "cumbia",             3],
  ["bossa_nova",     "bossa nova",         3],
  ["tropicalia",     "tropicália",         3],
  ["neo_soul",       "neo-soul",           7],
  ["conscious_rap",  "conscious rap",      5],
  ["trap",           "trap",               7],
  ["lo_fi_hip_hop",  "lo-fi hip-hop",      6],
  ["cloud_rap",      "cloud rap",          4],
  ["drill",          "drill",              4],
  ["boom_bap",       "boom bap",           6],
  ["abstract_hip_hop","abstract hip-hop",  5],
  ["spoken_word",    "spoken word",        3],
  ["field_recording","field recording",    4],
  ["acousmatic",     "acousmatic",         3],
  ["tape_music",     "tape music",         3],
  ["lowercase",      "lowercase",          2],
  ["power_electronics","power electronics",4],
  ["noise_ambient",  "noise ambient",      5],
  ["dark_ambient",   "dark ambient",       6],
  ["ritual_ambient", "ritual ambient",     4],
  ["liturgical",     "liturgical",         3],
  ["neofolk",        "neofolk",            5],
  ["post_industrial","post-industrial",    5],
  ["ebm",            "EBM",                4],
  ["synth_pop",      "synth-pop",          7],
  ["coldwave",       "coldwave",           4],
  ["ethereal",       "ethereal",           5],
  ["goth_rock",      "goth rock",          5],
  ["electro",        "electro",            5],
  ["idm",            "IDM",                8],
  ["glitch",         "glitch",             6],
  ["microsound",     "microsound",         3],
  ["clicks_cuts",    "clicks & cuts",      2],
  ["illbient",       "illbient",           3],
  ["trip_hop",       "trip-hop",           6],
  ["downtempo",      "downtempo",          6],
  ["chillout",       "chillout",           4],
  ["turntablism",    "turntablism",        3],
  ["spoken",         "spoken",             3],
  ["a_cappella",     "a cappella",         2],
  ["choral",         "choral",             3],
  ["orchestral",     "orchestral",         4],
  ["modern_classical","modern classical",  7],
  ["uk_garage",      "UK garage",          5],
  ["acid",           "acid",               4],
  ["witch_house",    "witch house",        4],
  ["ambient_techno", "ambient techno",     5],
  ["hyperpop",       "hyperpop",           4],
  ["post_dubstep",   "post-dubstep",       5],
  ["bass_music",     "bass music",         5],
  ["uk_jazz",        "UK jazz",            4],
  ["nu_jazz",        "nu jazz",            4],
  ["leftfield",      "leftfield",          5],
  ["noise_pop",      "noise pop",          4],
  ["contemporary_classical", "contemporary classical", 4],
];

export const LOCAL_TAGS: [string, string, number][] = [
  ["experimental", "experimental", 6],
  ["electronic", "electronic", 5],
  ["acoustic", "acoustic", 3],
  ["live", "live", 4],
  ["instrumental", "instrumental", 7],
  ["collaboration", "collab", 2],
  ["reissue", "reissue", 3],
  ["lo_fi", "lo-fi", 4],
];

export const LOCAL_ERAS: [string, string, number][] = [
  ["70s", "1970s", 4],
  ["80s", "1980s", 6],
  ["90s", "1990s", 8],
  ["00s", "2000s", 7],
  ["10s", "2010s", 9],
];

export const LOCAL_MOODS: [string, string][] = [
  ["dark",         "dark"],
  ["atmospheric",  "atmospheric"],
  ["meditative",   "meditative"],
  ["aggressive",   "aggressive"],
  ["melancholic",  "melancholic"],
  ["hypnotic",     "hypnotic"],
  ["haunting",     "haunting"],
  ["energetic",    "energetic"],
];
