export {
  musicBrainzApiMethods,
  MusicBrainzConfigSchema,
  MusicBrainzMatchSchema,
  SongWithMatchesSchema,
  SongMatchesResponseSchema,
  MusicBrainzSearchRequestSchema,
  MusicBrainzSearchResponseSchema,
  AlbumSearchRequestSchema,
  AlbumMatchSchema,
  AlbumSearchResponseSchema,
  type MusicBrainzConfig,
  type MusicBrainzMatch,
  type SongWithMatches,
  type SongMatchesResponse,
  type MusicBrainzSearchRequest,
  type MusicBrainzSearchResponse,
  type AlbumSearchRequest,
  type AlbumMatch,
  type AlbumSearchResponse,
} from "./api-methods.js";
