// generated route config
import * as s from './schema';
import { z } from 'zod';

export const routes = {
  music: {
    set_favorite: { method: 'POST', path: '/api/favorites/set', req: s.SetFavoriteRequestSchema, resp: s.SetFavoriteResponseSchema },
    list_favorites: { method: 'POST', path: '/api/favorites/list', req: s.ListFavoritesRequestSchema, resp: s.ListFavoritesResponseSchema },
    delete_artist: { method: 'DELETE', path: '/api/artists/{id}', req: s.DeleteArtistRequestSchema, resp: s.DeleteArtistResponseSchema },
    create_artist: { method: 'POST', path: '/api/music/artists', req: s.CreateArtistRequestSchema, resp: s.ArtistSchema },
    get_artist: { method: 'GET', path: '/api/artists/{id}', req: s.GetArtistRequestSchema, resp: s.ArtistSchema },
    query_artists: { method: 'POST', path: '/api/artists/query', req: s.QueryParamsSchema, resp: s.ArtistsQueryResultSchema },
    get_artist_images: { method: 'GET', path: '/api/artists/{id}/images', req: null, resp: z.string().array() },
    update_artist: { method: 'POST', path: '/api/artists/update', req: s.UpdateArtistRequestSchema, resp: s.ArtistSchema },
    query_tags: { method: 'POST', path: '/api/tags/query', req: s.QueryTagsRequestSchema, resp: s.TagSchema.array() },
    get_albums_tags: { method: 'POST', path: '/api/tags/albums/get', req: s.GetAlbumsTagsRequestSchema, resp: s.TagSchema.array() },
    remove_albums_tags: { method: 'POST', path: '/api/tags/albums/remove', req: s.RemoveAlbumsTagsRequestSchema, resp: s.EmptyResponseSchema },
    list_tags: { method: 'GET', path: '/api/tags/list', req: null, resp: s.TagSchema.array() },
    delete_tag: { method: 'POST', path: '/api/tags/delete', req: s.DeleteTagRequestSchema, resp: s.EmptyResponseSchema },
    replace_albums_tags: { method: 'POST', path: '/api/tags/albums/replace', req: s.ReplaceAlbumsTagsRequestSchema, resp: s.EmptyResponseSchema },
    add_albums_tags: { method: 'POST', path: '/api/tags/albums/add', req: s.AddAlbumsTagsRequestSchema, resp: s.EmptyResponseSchema },
    get_tag: { method: 'POST', path: '/api/tags/get', req: s.GetTagRequestSchema, resp: s.TagSchema },
    create_fetch_job: { method: 'POST', path: '/api/music/fetch', req: s.FetchMediaParamsSchema, resp: s.JobSchema },
    get_fetch_job: { method: 'GET', path: '/api/music/fetch/{id}', req: s.GetJobRequestSchema, resp: s.JobSchema },
    blob_metadata: { method: 'GET', path: '/api/blobs/{id}/metadata', req: null, resp: s.BlobMetadataResponseSchema },
    stream_blob: { method: 'GET', path: '/api/blobs/{id}', req: null, resp: null },
    update_album: { method: 'POST', path: '/api/albums/update', req: s.UpdateAlbumRequestSchema, resp: s.AlbumSchema },
    delete_album: { method: 'DELETE', path: '/api/albums/{id}', req: s.DeleteAlbumRequestSchema, resp: s.DeleteAlbumResponseSchema },
    get_album_images: { method: 'GET', path: '/api/albums/{id}/images', req: null, resp: z.string().array() },
    get_album: { method: 'GET', path: '/api/albums/{id}', req: s.GetAlbumRequestSchema, resp: s.AlbumSchema },
    query_albums: { method: 'POST', path: '/api/albums/query', req: s.QueryParamsSchema, resp: s.AlbumsQueryResultSchema },
    get_musicbrainz_release: { method: 'POST', path: '/api/musicbrainz/release', req: s.GetReleaseRequestSchema, resp: s.MbReleaseDetailSchema },
    search_musicbrainz_releases: { method: 'POST', path: '/api/musicbrainz/search/releases', req: s.SearchReleasesRequestSchema, resp: s.MbSearchReleasesResponseSchema },
    delete_playlist: { method: 'POST', path: '/api/playlists/delete', req: s.DeletePlaylistRequestSchema, resp: s.EmptyResponseSchema },
    list_playlists: { method: 'POST', path: '/api/music/playlists/list', req: s.QueryParamsSchema, resp: s.PlaylistsQueryResultSchema },
    create_playlist: { method: 'POST', path: '/api/music/playlists', req: s.CreatePlaylistRequestSchema, resp: s.PlaylistSchema },
    get_playlist_etag: { method: 'HEAD', path: '/api/music/playlists/{id}/etag', req: s.GetPlaylistRequestSchema, resp: null },
    add_songs_to_playlist: { method: 'POST', path: '/api/playlists/add-songs', req: s.AddSongsToPlaylistRequestSchema, resp: s.EmptyResponseSchema },
    query_playlist_songs: { method: 'POST', path: '/api/playlists/songs', req: s.QueryPlaylistSongsRequestSchema, resp: s.PlaylistSongsQueryResultSchema },
    reorder_playlist_songs: { method: 'POST', path: '/api/playlists/reorder', req: s.ReorderPlaylistSongsRequestSchema, resp: s.EmptyResponseSchema },
    update_playlist: { method: 'POST', path: '/api/playlists/update', req: s.UpdatePlaylistRequestSchema, resp: s.PlaylistSchema },
    get_playlist_images: { method: 'GET', path: '/api/playlists/{id}/images', req: null, resp: z.string().array() },
    get_playlist_by_id: { method: 'GET', path: '/api/music/playlists/{id}', req: s.GetPlaylistRequestSchema, resp: s.PlaylistSchema },
    remove_songs_from_playlist: { method: 'POST', path: '/api/playlists/remove-songs', req: s.RemoveSongsFromPlaylistRequestSchema, resp: s.EmptyResponseSchema },
    get_job_status: { method: 'POST', path: '/api/jobs/status', req: s.GetJobRequestSchema, resp: s.JobSchema },
    list_jobs: { method: 'POST', path: '/api/jobs/list', req: s.ListJobsRequestSchema, resp: s.JobSchema.array() },
    upload_music: { method: 'POST', path: '/api/upload/music', req: null, resp: s.MusicUploadResponseSchema },
    upload_image: { method: 'POST', path: '/api/upload/image', req: null, resp: s.ImageUploadResponseSchema },
    delete_image: { method: 'POST', path: '/api/music/images/delete', req: s.DeleteImageRequestSchema, resp: s.EmptyResponseSchema },
    set_primary_image: { method: 'POST', path: '/api/music/images/set-primary', req: s.SetPrimaryImageRequestSchema, resp: s.EmptyResponseSchema },
    get_rating_stats: { method: 'POST', path: '/api/ratings/stats', req: s.GetRatingStatsRequestSchema, resp: s.RatingStatsSchema },
    set_rating: { method: 'POST', path: '/api/ratings/set', req: s.SetRatingRequestSchema, resp: s.SetRatingResponseSchema },
    remove_rating: { method: 'POST', path: '/api/ratings/remove', req: s.RemoveRatingRequestSchema, resp: s.RemoveRatingResponseSchema },
    query_genres: { method: 'POST', path: '/api/genres/query', req: s.QueryParamsSchema, resp: s.GenresQueryResultSchema },
    get_genre: { method: 'GET', path: '/api/genres/{id}', req: s.GetGenreRequestSchema, resp: s.GenreSchema },
    recent_songs: { method: 'POST', path: '/api/songs/recent', req: s.RecentSongsRequestSchema, resp: s.SongsQueryResultSchema },
    delete_song: { method: 'DELETE', path: '/api/songs/{id}', req: s.DeleteSongRequestSchema, resp: s.DeleteSongResponseSchema },
    query_songs: { method: 'POST', path: '/api/songs/query', req: s.QueryParamsSchema, resp: s.SongsQueryResultSchema },
    update_songs: { method: 'POST', path: '/api/songs/update', req: s.UpdateSongsRequestSchema, resp: s.UpdateSongsResultSchema },
    search: { method: 'POST', path: '/api/music/search', req: s.SearchRequestSchema, resp: s.SearchResponseSchema },
    suggestions: { method: 'POST', path: '/api/music/suggestions', req: s.SuggestionsRequestSchema, resp: s.SuggestionsResponseSchema },
    update_listen_session_progress: { method: 'PUT', path: '/api/analytics/sessions/{id}/progress', req: s.UpdateListenSessionProgressRequestSchema, resp: s.EmptyResponseSchema },
    top_artists: { method: 'POST', path: '/api/analytics/top-artists', req: s.TopArtistsRequestSchema, resp: s.TopArtistSchema.array() },
    list_listen_sessions: { method: 'POST', path: '/api/analytics/sessions/list', req: s.ListListenSessionsRequestSchema, resp: s.ListListenSessionsResponseSchema },
    top_albums: { method: 'POST', path: '/api/analytics/top-albums', req: s.TopAlbumsRequestSchema, resp: s.TopAlbumSchema.array() },
    update_listen_session_songs: { method: 'PUT', path: '/api/analytics/sessions/{id}/songs', req: s.UpdateListenSessionSongsRequestSchema, resp: s.EmptyResponseSchema },
    delete_listen_session: { method: 'DELETE', path: '/api/analytics/sessions/{id}', req: null, resp: s.EmptyResponseSchema },
    song_analytics: { method: 'POST', path: '/api/analytics/song-stats', req: s.SongAnalyticsRequestSchema, resp: s.PlayAnalyticsSchema },
    record_play: { method: 'POST', path: '/api/analytics/play', req: s.RecordPlayRequestSchema, resp: s.EmptyResponseSchema },
    get_listen_session: { method: 'GET', path: '/api/analytics/sessions/{id}', req: null, resp: s.ListenSessionSchema },
    update_listen_session_status: { method: 'PUT', path: '/api/analytics/sessions/{id}/status/{status}', req: null, resp: s.EmptyResponseSchema },
    top_songs: { method: 'POST', path: '/api/analytics/top-songs', req: s.TopSongsRequestSchema, resp: s.TopSongSchema.array() },
    create_listen_session: { method: 'POST', path: '/api/analytics/sessions', req: s.CreateListenSessionRequestSchema, resp: s.ListenSessionSchema },
    activity_feed: { method: 'POST', path: '/api/analytics/feed', req: s.FeedRequestSchema, resp: s.FeedResponseSchema },
    listening_history: { method: 'POST', path: '/api/analytics/listening-history', req: s.ListeningHistoryRequestSchema, resp: s.ListeningHistoryResponseSchema },
  },
  auth: {
    redeem_invite: { method: 'POST', path: '/api/auth/invite', req: s.RedeemInviteRequestSchema, resp: z.any() },
    whoami: { method: 'GET', path: '/api/auth/whoami', req: null, resp: s.WhoAmIResponseSchema },
    regenerate_api_key: { method: 'POST', path: '/api/auth/api-key/regenerate', req: null, resp: s.ApiKeyRegenerateResponseSchema },
    api_key_status: { method: 'GET', path: '/api/auth/api-key/status', req: null, resp: s.ApiKeyStatusResponseSchema },
    logout: { method: 'POST', path: '/api/auth/logout', req: null, resp: z.any() },
    login_finish: { method: 'POST', path: '/api/auth/webauthn/login/finish', req: z.any(), resp: z.any() },
    register_start: { method: 'POST', path: '/api/auth/webauthn/register/start', req: s.RegisterStartRequestSchema, resp: z.any() },
    register_finish: { method: 'POST', path: '/api/auth/webauthn/register/finish', req: z.any(), resp: z.any() },
    login_start: { method: 'POST', path: '/api/auth/webauthn/login/start', req: s.StartLoginRequestSchema, resp: z.any() },
  },
  app: {
    server_info: { method: 'GET', path: '/api/hello', req: null, resp: s.ServerInfoResponseSchema },
    health_check: { method: 'GET', path: '/health', req: null, resp: s.HealthResponseSchema },
  },
};
