// Automatically generated by zod_gen
import * as z from 'zod';

export const ApiKeyRegenerateResponseSchema = z.object({
  api_key: z.string(),
  message: z.string()
});
export type ApiKeyRegenerateResponse = z.infer<typeof ApiKeyRegenerateResponseSchema>;

export const ApiKeyStatusResponseSchema = z.object({
  has_api_key: z.boolean(),
  api_key_preview: z.string().nullable()
});
export type ApiKeyStatusResponse = z.infer<typeof ApiKeyStatusResponseSchema>;

export const PlaylistSchema = z.object({
  id: z.string(),
  title: z.string(),
  description: z.string().nullable(),
  is_public: z.number(),
  thumbnail_blob_id: z.string().nullable(),
  created_by_id: z.string().nullable(),
  created_at: z.number(),
  updated_at: z.number(),
  deleted_at: z.number().nullable(),
  deleted_by: z.string().nullable(),
  created_by: z.string().nullable(),
  updated_by: z.string().nullable(),
  song_count: z.number()
});
export type Playlist = z.infer<typeof PlaylistSchema>;

export const PlaylistQueryResultSchema = z.object({
  playlist: z.object({
  id: z.string(),
  title: z.string(),
  description: z.string().nullable(),
  is_public: z.number(),
  thumbnail_blob_id: z.string().nullable(),
  created_by_id: z.string().nullable(),
  created_at: z.number(),
  updated_at: z.number(),
  deleted_at: z.number().nullable(),
  deleted_by: z.string().nullable(),
  created_by: z.string().nullable(),
  updated_by: z.string().nullable(),
  song_count: z.number()
}),
  song_count: z.number(),
  total_duration: z.number().nullable(),
  is_favorite: z.boolean().nullable()
});
export type PlaylistQueryResult = z.infer<typeof PlaylistQueryResultSchema>;

export const QueryParamsSchema = z.object({
  q: z.string().nullable(),
  search_fields: z.array(z.string()).nullable(),
  filters: z.record(z.string(), z.any()),
  sort_by: z.string().nullable(),
  sort_direction: z.string().nullable(),
  limit: z.number().nullable(),
  offset: z.number().nullable(),
  user_id: z.string().nullable(),
  favorites_only: z.boolean().nullable(),
  min_rating: z.number().nullable()
});
export type QueryParams = z.infer<typeof QueryParamsSchema>;

export const RedeemInviteRequestSchema = z.object({
  invite_code: z.string(),
  username: z.string()
});
export type RedeemInviteRequest = z.infer<typeof RedeemInviteRequestSchema>;

export const WhoAmIResponseSchema = z.object({
  user_id: z.string(),
  username: z.string(),
  role: z.string()
});
export type WhoAmIResponse = z.infer<typeof WhoAmIResponseSchema>;

