// Automatically generated by zod_gen
import * as z from 'zod';

export const AddAlbumsTagsRequestSchema = z.object({
  album_ids: z.array(z.string()),
  tag_ids: z.array(z.string()),
  tag_names: z.array(z.string())
});
export type AddAlbumsTagsRequest = z.infer<typeof AddAlbumsTagsRequestSchema>;

export const AddSongsToPlaylistRequestSchema = z.object({
  playlist_id: z.string(),
  song_ids: z.array(z.string())
});
export type AddSongsToPlaylistRequest = z.infer<typeof AddSongsToPlaylistRequestSchema>;

export const AlbumSchema = z.object({
  id: z.string(),
  title: z.string(),
  album_type: z.string(),
  release_date: z.string().nullable(),
  label: z.string().nullable(),
  genres: z.array(z.object({
  id: z.string(),
  name: z.string()
})).nullable(),
  images: z.array(z.object({
  blob_id: z.string(),
  is_primary: z.number(),
  blob_type: z.union([z.literal("original"), z.literal("thumbnail"), z.literal("waveform"), z.literal("preview")])
})).nullable(),
  urls: z.array(z.object({
  id: z.string().nullable(),
  name: z.string().nullable(),
  url: z.string()
})).nullable(),
  song_count: z.number(),
  total_duration: z.number(),
  created_at: z.number(),
  updated_at: z.number(),
  deleted_at: z.number().nullable(),
  deleted_by: z.string().nullable(),
  created_by: z.string().nullable(),
  updated_by: z.string().nullable()
});
export type Album = z.infer<typeof AlbumSchema>;

export const AlbumQueryResultSchema = z.object({
  album: z.object({
  id: z.string(),
  title: z.string(),
  album_type: z.string(),
  release_date: z.string().nullable(),
  label: z.string().nullable(),
  genres: z.array(z.object({
  id: z.string(),
  name: z.string()
})).nullable(),
  images: z.array(z.object({
  blob_id: z.string(),
  is_primary: z.number(),
  blob_type: z.union([z.literal("original"), z.literal("thumbnail"), z.literal("waveform"), z.literal("preview")])
})).nullable(),
  urls: z.array(z.object({
  id: z.string().nullable(),
  name: z.string().nullable(),
  url: z.string()
})).nullable(),
  song_count: z.number(),
  total_duration: z.number(),
  created_at: z.number(),
  updated_at: z.number(),
  deleted_at: z.number().nullable(),
  deleted_by: z.string().nullable(),
  created_by: z.string().nullable(),
  updated_by: z.string().nullable()
}),
  artist: z.object({
  id: z.string(),
  name: z.string(),
  bio: z.string().nullable(),
  images: z.array(z.object({
  blob_id: z.string(),
  is_primary: z.number(),
  blob_type: z.union([z.literal("original"), z.literal("thumbnail"), z.literal("waveform"), z.literal("preview")])
})).nullable(),
  urls: z.array(z.object({
  id: z.string().nullable(),
  name: z.string().nullable(),
  url: z.string()
})).nullable(),
  created_at: z.number(),
  updated_at: z.number(),
  deleted_at: z.number().nullable(),
  deleted_by: z.string().nullable(),
  created_by: z.string().nullable(),
  updated_by: z.string().nullable()
}).nullable(),
  genre: z.object({
  id: z.string(),
  name: z.string(),
  created_at: z.number()
}).nullable(),
  images: z.array(z.object({
  blob_id: z.string(),
  is_primary: z.number(),
  blob_type: z.union([z.literal("original"), z.literal("thumbnail"), z.literal("waveform"), z.literal("preview")])
})).nullable(),
  album_tags: z.array(z.string()).nullable(),
  is_favorite: z.boolean().nullable(),
  rating: z.number().nullable(),
  favorited_at: z.number().nullable(),
  rating_created_at: z.number().nullable()
});
export type AlbumQueryResult = z.infer<typeof AlbumQueryResultSchema>;

export const AlbumSearchResultSchema = z.object({
  id: z.string(),
  title: z.string(),
  artist_names: z.array(z.string()),
  genres: z.array(z.string()),
  song_count: z.number(),
  thumbnail_url: z.string().nullable(),
  user_rating: z.number().nullable(),
  is_favorite: z.boolean(),
  search_rank: z.number(),
  highlight: z.string().nullable()
});
export type AlbumSearchResult = z.infer<typeof AlbumSearchResultSchema>;

export const AlbumsQueryResultSchema = z.object({
  items: z.array(z.object({
  album: z.object({
  id: z.string(),
  title: z.string(),
  album_type: z.string(),
  release_date: z.string().nullable(),
  label: z.string().nullable(),
  genres: z.array(z.object({
  id: z.string(),
  name: z.string()
})).nullable(),
  images: z.array(z.object({
  blob_id: z.string(),
  is_primary: z.number(),
  blob_type: z.union([z.literal("original"), z.literal("thumbnail"), z.literal("waveform"), z.literal("preview")])
})).nullable(),
  urls: z.array(z.object({
  id: z.string().nullable(),
  name: z.string().nullable(),
  url: z.string()
})).nullable(),
  song_count: z.number(),
  total_duration: z.number(),
  created_at: z.number(),
  updated_at: z.number(),
  deleted_at: z.number().nullable(),
  deleted_by: z.string().nullable(),
  created_by: z.string().nullable(),
  updated_by: z.string().nullable()
}),
  artist: z.object({
  id: z.string(),
  name: z.string(),
  bio: z.string().nullable(),
  images: z.array(z.object({
  blob_id: z.string(),
  is_primary: z.number(),
  blob_type: z.union([z.literal("original"), z.literal("thumbnail"), z.literal("waveform"), z.literal("preview")])
})).nullable(),
  urls: z.array(z.object({
  id: z.string().nullable(),
  name: z.string().nullable(),
  url: z.string()
})).nullable(),
  created_at: z.number(),
  updated_at: z.number(),
  deleted_at: z.number().nullable(),
  deleted_by: z.string().nullable(),
  created_by: z.string().nullable(),
  updated_by: z.string().nullable()
}).nullable(),
  genre: z.object({
  id: z.string(),
  name: z.string(),
  created_at: z.number()
}).nullable(),
  images: z.array(z.object({
  blob_id: z.string(),
  is_primary: z.number(),
  blob_type: z.union([z.literal("original"), z.literal("thumbnail"), z.literal("waveform"), z.literal("preview")])
})).nullable(),
  album_tags: z.array(z.string()).nullable(),
  is_favorite: z.boolean().nullable(),
  rating: z.number().nullable(),
  favorited_at: z.number().nullable(),
  rating_created_at: z.number().nullable()
})),
  total_count: z.number(),
  has_more: z.boolean(),
  offset: z.number(),
  limit: z.number(),
  query_time_ms: z.number().nullable()
});
export type AlbumsQueryResult = z.infer<typeof AlbumsQueryResultSchema>;

export const ApiKeyRegenerateResponseSchema = z.object({
  api_key: z.string(),
  message: z.string()
});
export type ApiKeyRegenerateResponse = z.infer<typeof ApiKeyRegenerateResponseSchema>;

export const ApiKeyStatusResponseSchema = z.object({
  has_api_key: z.boolean(),
  api_key_preview: z.string().nullable()
});
export type ApiKeyStatusResponse = z.infer<typeof ApiKeyStatusResponseSchema>;

export const ArtistSchema = z.object({
  id: z.string(),
  name: z.string(),
  bio: z.string().nullable(),
  images: z.array(z.object({
  blob_id: z.string(),
  is_primary: z.number(),
  blob_type: z.union([z.literal("original"), z.literal("thumbnail"), z.literal("waveform"), z.literal("preview")])
})).nullable(),
  urls: z.array(z.object({
  id: z.string().nullable(),
  name: z.string().nullable(),
  url: z.string()
})).nullable(),
  created_at: z.number(),
  updated_at: z.number(),
  deleted_at: z.number().nullable(),
  deleted_by: z.string().nullable(),
  created_by: z.string().nullable(),
  updated_by: z.string().nullable()
});
export type Artist = z.infer<typeof ArtistSchema>;

export const ArtistQueryResultSchema = z.object({
  artist: z.object({
  id: z.string(),
  name: z.string(),
  bio: z.string().nullable(),
  images: z.array(z.object({
  blob_id: z.string(),
  is_primary: z.number(),
  blob_type: z.union([z.literal("original"), z.literal("thumbnail"), z.literal("waveform"), z.literal("preview")])
})).nullable(),
  urls: z.array(z.object({
  id: z.string().nullable(),
  name: z.string().nullable(),
  url: z.string()
})).nullable(),
  created_at: z.number(),
  updated_at: z.number(),
  deleted_at: z.number().nullable(),
  deleted_by: z.string().nullable(),
  created_by: z.string().nullable(),
  updated_by: z.string().nullable()
}),
  images: z.array(z.object({
  blob_id: z.string(),
  is_primary: z.number(),
  blob_type: z.union([z.literal("original"), z.literal("thumbnail"), z.literal("waveform"), z.literal("preview")])
})).nullable(),
  song_count: z.number(),
  album_count: z.number(),
  total_duration: z.number().nullable(),
  is_favorite: z.boolean().nullable(),
  rating: z.number().nullable(),
  favorited_at: z.number().nullable(),
  rating_created_at: z.number().nullable()
});
export type ArtistQueryResult = z.infer<typeof ArtistQueryResultSchema>;

export const ArtistSearchResultSchema = z.object({
  id: z.string(),
  name: z.string(),
  song_count: z.number(),
  album_count: z.number(),
  genres: z.array(z.string()),
  user_rating: z.number().nullable(),
  is_favorite: z.boolean(),
  search_rank: z.number(),
  highlight: z.string().nullable()
});
export type ArtistSearchResult = z.infer<typeof ArtistSearchResultSchema>;

export const ArtistsQueryResultSchema = z.object({
  items: z.array(z.object({
  artist: z.object({
  id: z.string(),
  name: z.string(),
  bio: z.string().nullable(),
  images: z.array(z.object({
  blob_id: z.string(),
  is_primary: z.number(),
  blob_type: z.union([z.literal("original"), z.literal("thumbnail"), z.literal("waveform"), z.literal("preview")])
})).nullable(),
  urls: z.array(z.object({
  id: z.string().nullable(),
  name: z.string().nullable(),
  url: z.string()
})).nullable(),
  created_at: z.number(),
  updated_at: z.number(),
  deleted_at: z.number().nullable(),
  deleted_by: z.string().nullable(),
  created_by: z.string().nullable(),
  updated_by: z.string().nullable()
}),
  images: z.array(z.object({
  blob_id: z.string(),
  is_primary: z.number(),
  blob_type: z.union([z.literal("original"), z.literal("thumbnail"), z.literal("waveform"), z.literal("preview")])
})).nullable(),
  song_count: z.number(),
  album_count: z.number(),
  total_duration: z.number().nullable(),
  is_favorite: z.boolean().nullable(),
  rating: z.number().nullable(),
  favorited_at: z.number().nullable(),
  rating_created_at: z.number().nullable()
})),
  total_count: z.number(),
  has_more: z.boolean(),
  offset: z.number(),
  limit: z.number(),
  query_time_ms: z.number().nullable()
});
export type ArtistsQueryResult = z.infer<typeof ArtistsQueryResultSchema>;

export const AssociationHintSchema = z.object({
  entity_type: z.string(),
  entity_id: z.string(),
  is_primary: z.boolean().nullable()
});
export type AssociationHint = z.infer<typeof AssociationHintSchema>;

export const AssociationInfoSchema = z.object({
  entity_type: z.string(),
  entity_id: z.string()
});
export type AssociationInfo = z.infer<typeof AssociationInfoSchema>;

export const BlobMetadataResponseSchema = z.object({
  id: z.string(),
  sha256: z.string(),
  size: z.number().nullable(),
  mime: z.string().nullable(),
  filename: z.string().nullable(),
  blob_type: z.union([z.literal("original"), z.literal("thumbnail"), z.literal("waveform"), z.literal("preview")])
});
export type BlobMetadataResponse = z.infer<typeof BlobMetadataResponseSchema>;

export const CreateArtistRequestSchema = z.object({
  name: z.string(),
  created_by: z.string().nullable()
});
export type CreateArtistRequest = z.infer<typeof CreateArtistRequestSchema>;

export const CreateJobRequestSchema = z.object({
  job_type: z.union([z.literal('ScanDirectory'), z.literal('RescanDirectories'), z.literal('ProcessFile'), z.literal('FetchMedia'), z.literal('ConvertWebp'), z.literal('ImportMusic')]),
  session_id: z.string().nullable(),
  parameters: z.any(),
  max_retries: z.number().nullable(),
  scheduled_at: z.number().nullable(),
  created_by: z.string().nullable()
});
export type CreateJobRequest = z.infer<typeof CreateJobRequestSchema>;

export const CreatePlaylistRequestSchema = z.object({
  title: z.string().nullable(),
  description: z.string().nullable(),
  is_public: z.boolean().nullable(),
  created_by_id: z.string().nullable()
});
export type CreatePlaylistRequest = z.infer<typeof CreatePlaylistRequestSchema>;

export const CreateTagRequestSchema = z.object({
  name: z.string()
});
export type CreateTagRequest = z.infer<typeof CreateTagRequestSchema>;

export const DeleteAlbumRequestSchema = z.object({
  id: z.string(),
  user_id: z.string().nullable()
});
export type DeleteAlbumRequest = z.infer<typeof DeleteAlbumRequestSchema>;

export const DeleteAlbumResponseSchema = z.object({
  success: z.boolean(),
  message: z.string()
});
export type DeleteAlbumResponse = z.infer<typeof DeleteAlbumResponseSchema>;

export const DeleteArtistRequestSchema = z.object({
  id: z.string(),
  user_id: z.string().nullable()
});
export type DeleteArtistRequest = z.infer<typeof DeleteArtistRequestSchema>;

export const DeleteArtistResponseSchema = z.object({
  success: z.boolean(),
  message: z.string()
});
export type DeleteArtistResponse = z.infer<typeof DeleteArtistResponseSchema>;

export const DeleteImageRequestSchema = z.object({
  entity_type: z.string(),
  entity_id: z.string(),
  blob_id: z.string()
});
export type DeleteImageRequest = z.infer<typeof DeleteImageRequestSchema>;

export const DeletePlaylistRequestSchema = z.object({
  playlist_id: z.string(),
  deleted_by: z.string().nullable()
});
export type DeletePlaylistRequest = z.infer<typeof DeletePlaylistRequestSchema>;

export const DeleteSongRequestSchema = z.object({
  id: z.string(),
  user_id: z.string().nullable()
});
export type DeleteSongRequest = z.infer<typeof DeleteSongRequestSchema>;

export const DeleteSongResponseSchema = z.object({
  success: z.boolean(),
  message: z.string()
});
export type DeleteSongResponse = z.infer<typeof DeleteSongResponseSchema>;

export const DeleteTagRequestSchema = z.object({
  tag_id: z.string(),
  deleted_by: z.string().nullable()
});
export type DeleteTagRequest = z.infer<typeof DeleteTagRequestSchema>;

export const EmptyResponseSchema = z.object({
  success: z.boolean()
});
export type EmptyResponse = z.infer<typeof EmptyResponseSchema>;

export const FavoriteAlbumResultSchema = z.object({
  favorited_at: z.number(),
  album: z.object({
  album: z.object({
  id: z.string(),
  title: z.string(),
  album_type: z.string(),
  release_date: z.string().nullable(),
  label: z.string().nullable(),
  genres: z.array(z.object({
  id: z.string(),
  name: z.string()
})).nullable(),
  images: z.array(z.object({
  blob_id: z.string(),
  is_primary: z.number(),
  blob_type: z.union([z.literal("original"), z.literal("thumbnail"), z.literal("waveform"), z.literal("preview")])
})).nullable(),
  urls: z.array(z.object({
  id: z.string().nullable(),
  name: z.string().nullable(),
  url: z.string()
})).nullable(),
  song_count: z.number(),
  total_duration: z.number(),
  created_at: z.number(),
  updated_at: z.number(),
  deleted_at: z.number().nullable(),
  deleted_by: z.string().nullable(),
  created_by: z.string().nullable(),
  updated_by: z.string().nullable()
}),
  artist: z.object({
  id: z.string(),
  name: z.string(),
  bio: z.string().nullable(),
  images: z.array(z.object({
  blob_id: z.string(),
  is_primary: z.number(),
  blob_type: z.union([z.literal("original"), z.literal("thumbnail"), z.literal("waveform"), z.literal("preview")])
})).nullable(),
  urls: z.array(z.object({
  id: z.string().nullable(),
  name: z.string().nullable(),
  url: z.string()
})).nullable(),
  created_at: z.number(),
  updated_at: z.number(),
  deleted_at: z.number().nullable(),
  deleted_by: z.string().nullable(),
  created_by: z.string().nullable(),
  updated_by: z.string().nullable()
}).nullable(),
  genre: z.object({
  id: z.string(),
  name: z.string(),
  created_at: z.number()
}).nullable(),
  images: z.array(z.object({
  blob_id: z.string(),
  is_primary: z.number(),
  blob_type: z.union([z.literal("original"), z.literal("thumbnail"), z.literal("waveform"), z.literal("preview")])
})).nullable(),
  album_tags: z.array(z.string()).nullable(),
  is_favorite: z.boolean().nullable(),
  rating: z.number().nullable(),
  favorited_at: z.number().nullable(),
  rating_created_at: z.number().nullable()
})
});
export type FavoriteAlbumResult = z.infer<typeof FavoriteAlbumResultSchema>;

export const FavoriteArtistResultSchema = z.object({
  favorited_at: z.number(),
  artist: z.object({
  artist: z.object({
  id: z.string(),
  name: z.string(),
  bio: z.string().nullable(),
  images: z.array(z.object({
  blob_id: z.string(),
  is_primary: z.number(),
  blob_type: z.union([z.literal("original"), z.literal("thumbnail"), z.literal("waveform"), z.literal("preview")])
})).nullable(),
  urls: z.array(z.object({
  id: z.string().nullable(),
  name: z.string().nullable(),
  url: z.string()
})).nullable(),
  created_at: z.number(),
  updated_at: z.number(),
  deleted_at: z.number().nullable(),
  deleted_by: z.string().nullable(),
  created_by: z.string().nullable(),
  updated_by: z.string().nullable()
}),
  images: z.array(z.object({
  blob_id: z.string(),
  is_primary: z.number(),
  blob_type: z.union([z.literal("original"), z.literal("thumbnail"), z.literal("waveform"), z.literal("preview")])
})).nullable(),
  song_count: z.number(),
  album_count: z.number(),
  total_duration: z.number().nullable(),
  is_favorite: z.boolean().nullable(),
  rating: z.number().nullable(),
  favorited_at: z.number().nullable(),
  rating_created_at: z.number().nullable()
})
});
export type FavoriteArtistResult = z.infer<typeof FavoriteArtistResultSchema>;

export const FavoriteItemSchema = z.union([z.literal('Song'), z.literal('Album'), z.literal('Artist'), z.literal('Playlist')]);
export type FavoriteItem = z.infer<typeof FavoriteItemSchema>;

export const FavoritePlaylistResultSchema = z.object({
  favorited_at: z.number(),
  playlist: z.object({
  playlist: z.object({
  id: z.string(),
  title: z.string(),
  description: z.string().nullable(),
  is_public: z.number(),
  images: z.array(z.object({
  blob_id: z.string(),
  is_primary: z.number(),
  blob_type: z.union([z.literal("original"), z.literal("thumbnail"), z.literal("waveform"), z.literal("preview")])
})).nullable(),
  urls: z.array(z.object({
  id: z.string().nullable(),
  name: z.string().nullable(),
  url: z.string()
})).nullable(),
  created_by_id: z.string().nullable(),
  created_at: z.number(),
  updated_at: z.number(),
  deleted_at: z.number().nullable(),
  deleted_by: z.string().nullable(),
  created_by: z.string().nullable(),
  updated_by: z.string().nullable(),
  song_count: z.number()
}),
  song_count: z.number(),
  total_duration: z.number().nullable(),
  is_favorite: z.boolean().nullable()
})
});
export type FavoritePlaylistResult = z.infer<typeof FavoritePlaylistResultSchema>;

export const FavoriteSongResultSchema = z.object({
  favorited_at: z.number(),
  song: z.object({
  song: z.object({
  id: z.string(),
  media_blob_id: z.string(),
  images: z.array(z.object({
  blob_id: z.string(),
  is_primary: z.number(),
  blob_type: z.union([z.literal("original"), z.literal("thumbnail"), z.literal("waveform"), z.literal("preview")])
})).nullable(),
  urls: z.array(z.object({
  id: z.string().nullable(),
  name: z.string().nullable(),
  url: z.string()
})).nullable(),
  title: z.string(),
  track_number: z.number(),
  disc_number: z.number(),
  duration: z.number().nullable(),
  bpm: z.number().nullable(),
  track_artist: z.string().nullable(),
  metadata: z.string().nullable(),
  lyrics: z.string().nullable(),
  created_at: z.number(),
  updated_at: z.number(),
  deleted_at: z.number().nullable(),
  deleted_by: z.string().nullable(),
  created_by: z.string().nullable(),
  updated_by: z.string().nullable()
}),
  artist: z.object({
  id: z.string(),
  name: z.string(),
  bio: z.string().nullable(),
  images: z.array(z.object({
  blob_id: z.string(),
  is_primary: z.number(),
  blob_type: z.union([z.literal("original"), z.literal("thumbnail"), z.literal("waveform"), z.literal("preview")])
})).nullable(),
  urls: z.array(z.object({
  id: z.string().nullable(),
  name: z.string().nullable(),
  url: z.string()
})).nullable(),
  created_at: z.number(),
  updated_at: z.number(),
  deleted_at: z.number().nullable(),
  deleted_by: z.string().nullable(),
  created_by: z.string().nullable(),
  updated_by: z.string().nullable()
}).nullable(),
  album: z.object({
  id: z.string(),
  title: z.string(),
  album_type: z.string(),
  release_date: z.string().nullable(),
  label: z.string().nullable(),
  genres: z.array(z.object({
  id: z.string(),
  name: z.string()
})).nullable(),
  images: z.array(z.object({
  blob_id: z.string(),
  is_primary: z.number(),
  blob_type: z.union([z.literal("original"), z.literal("thumbnail"), z.literal("waveform"), z.literal("preview")])
})).nullable(),
  urls: z.array(z.object({
  id: z.string().nullable(),
  name: z.string().nullable(),
  url: z.string()
})).nullable(),
  song_count: z.number(),
  total_duration: z.number(),
  created_at: z.number(),
  updated_at: z.number(),
  deleted_at: z.number().nullable(),
  deleted_by: z.string().nullable(),
  created_by: z.string().nullable(),
  updated_by: z.string().nullable()
}).nullable(),
  genre: z.object({
  id: z.string(),
  name: z.string(),
  created_at: z.number()
}).nullable(),
  media_blob: z.object({
  id: z.string(),
  sha256: z.string(),
  size: z.number().nullable(),
  mime: z.string().nullable(),
  source_client_id: z.string().nullable(),
  filename: z.string().nullable(),
  parent_blob_id: z.string().nullable(),
  blob_type: z.union([z.literal("original"), z.literal("thumbnail"), z.literal("waveform"), z.literal("preview")]),
  metadata: z.any(),
  created_at: z.number(),
  updated_at: z.number(),
  deleted_at: z.number().nullable(),
  deleted_by: z.string().nullable(),
  created_by: z.string().nullable(),
  updated_by: z.string().nullable()
}).nullable(),
  images: z.array(z.object({
  blob_id: z.string(),
  is_primary: z.number(),
  blob_type: z.union([z.literal("original"), z.literal("thumbnail"), z.literal("waveform"), z.literal("preview")])
})).nullable(),
  relevance_score: z.number().nullable(),
  snippet: z.string().nullable(),
  is_favorite: z.boolean().nullable(),
  rating: z.number().nullable(),
  favorited_at: z.number().nullable(),
  rating_created_at: z.number().nullable(),
  artist_total_song_count: z.number().nullable(),
  artist_total_album_count: z.number().nullable(),
  artist_total_duration: z.number().nullable(),
  album_is_favorite: z.boolean().nullable(),
  album_rating: z.number().nullable(),
  album_tags: z.array(z.string()).nullable()
})
});
export type FavoriteSongResult = z.infer<typeof FavoriteSongResultSchema>;

export const FeedItemSchema = z.object({
  id: z.string(),
  feed_type: z.union([z.literal('RecentListen'), z.literal('RecentFavorite'), z.literal('RecentAlbum')]),
  song_id: z.string().nullable(),
  album_id: z.string().nullable(),
  artist_id: z.string().nullable(),
  title: z.string(),
  subtitle: z.string().nullable(),
  images: z.array(z.object({
  blob_id: z.string(),
  is_primary: z.number(),
  blob_type: z.union([z.literal("original"), z.literal("thumbnail"), z.literal("waveform"), z.literal("preview")])
})).nullable(),
  created_at: z.number(),
  user_id: z.string().nullable(),
  username: z.string().nullable(),
  play_count: z.number().nullable()
});
export type FeedItem = z.infer<typeof FeedItemSchema>;

export const FeedItemTypeSchema = z.union([z.literal('RecentListen'), z.literal('RecentFavorite'), z.literal('RecentAlbum')]);
export type FeedItemType = z.infer<typeof FeedItemTypeSchema>;

export const FeedRequestSchema = z.object({
  limit: z.number().nullable(),
  offset: z.number().nullable()
});
export type FeedRequest = z.infer<typeof FeedRequestSchema>;

export const FeedResponseSchema = z.object({
  items: z.array(z.object({
  id: z.string(),
  feed_type: z.union([z.literal('RecentListen'), z.literal('RecentFavorite'), z.literal('RecentAlbum')]),
  song_id: z.string().nullable(),
  album_id: z.string().nullable(),
  artist_id: z.string().nullable(),
  title: z.string(),
  subtitle: z.string().nullable(),
  images: z.array(z.object({
  blob_id: z.string(),
  is_primary: z.number(),
  blob_type: z.union([z.literal("original"), z.literal("thumbnail"), z.literal("waveform"), z.literal("preview")])
})).nullable(),
  created_at: z.number(),
  user_id: z.string().nullable(),
  username: z.string().nullable(),
  play_count: z.number().nullable()
})),
  total: z.number()
});
export type FeedResponse = z.infer<typeof FeedResponseSchema>;

export const FetchMediaParamsSchema = z.object({
  url: z.string(),
  user_id: z.string().nullable()
});
export type FetchMediaParams = z.infer<typeof FetchMediaParamsSchema>;

export const FetchMediaResultSchema = z.object({
  items_requested: z.number(),
  items_downloaded: z.number(),
  items_failed: z.number(),
  media_blob_ids: z.array(z.string()),
  song_ids: z.array(z.string()),
  errors: z.array(z.string())
});
export type FetchMediaResult = z.infer<typeof FetchMediaResultSchema>;

export const FilterSetSchema = z.object({
  include: z.array(z.string()),
  exclude: z.array(z.string())
});
export type FilterSet = z.infer<typeof FilterSetSchema>;

export const GenreSchema = z.object({
  id: z.string(),
  name: z.string(),
  created_at: z.number()
});
export type Genre = z.infer<typeof GenreSchema>;

export const GenreQueryResultSchema = z.object({
  genre: z.object({
  id: z.string(),
  name: z.string(),
  created_at: z.number()
}),
  song_count: z.number().nullable(),
  album_count: z.number().nullable(),
  is_favorite: z.boolean().nullable(),
  favorited_at: z.number().nullable()
});
export type GenreQueryResult = z.infer<typeof GenreQueryResultSchema>;

export const GenreRefSchema = z.object({
  id: z.string(),
  name: z.string()
});
export type GenreRef = z.infer<typeof GenreRefSchema>;

export const GenreSearchResultSchema = z.object({
  genre: z.string(),
  genre_id: z.string(),
  song_count: z.number(),
  artist_count: z.number(),
  representative_song_id: z.string().nullable(),
  representative_thumbnail: z.string().nullable(),
  avg_rating: z.number().nullable(),
  search_rank: z.number()
});
export type GenreSearchResult = z.infer<typeof GenreSearchResultSchema>;

export const GenresQueryResultSchema = z.object({
  items: z.array(z.object({
  genre: z.object({
  id: z.string(),
  name: z.string(),
  created_at: z.number()
}),
  song_count: z.number().nullable(),
  album_count: z.number().nullable(),
  is_favorite: z.boolean().nullable(),
  favorited_at: z.number().nullable()
})),
  total_count: z.number(),
  has_more: z.boolean(),
  offset: z.number(),
  limit: z.number(),
  query_time_ms: z.number().nullable()
});
export type GenresQueryResult = z.infer<typeof GenresQueryResultSchema>;

export const GetAlbumRequestSchema = z.object({
  id: z.string()
});
export type GetAlbumRequest = z.infer<typeof GetAlbumRequestSchema>;

export const GetAlbumsTagsRequestSchema = z.object({
  album_ids: z.array(z.string())
});
export type GetAlbumsTagsRequest = z.infer<typeof GetAlbumsTagsRequestSchema>;

export const GetArtistRequestSchema = z.object({
  id: z.string()
});
export type GetArtistRequest = z.infer<typeof GetArtistRequestSchema>;

export const GetCoverArtRequestSchema = z.object({
  mbid: z.string()
});
export type GetCoverArtRequest = z.infer<typeof GetCoverArtRequestSchema>;

export const GetGenreRequestSchema = z.object({
  id: z.string()
});
export type GetGenreRequest = z.infer<typeof GetGenreRequestSchema>;

export const GetJobRequestSchema = z.object({
  job_id: z.string()
});
export type GetJobRequest = z.infer<typeof GetJobRequestSchema>;

export const GetPlaylistRequestSchema = z.object({
  id: z.string()
});
export type GetPlaylistRequest = z.infer<typeof GetPlaylistRequestSchema>;

export const GetRatingStatsRequestSchema = z.object({
  target_type: z.union([z.literal("song"), z.literal("artist"), z.literal("album")]),
  target_id: z.string()
});
export type GetRatingStatsRequest = z.infer<typeof GetRatingStatsRequestSchema>;

export const GetRecordingRequestSchema = z.object({
  mbid: z.string()
});
export type GetRecordingRequest = z.infer<typeof GetRecordingRequestSchema>;

export const GetReleaseRequestSchema = z.object({
  mbid: z.string()
});
export type GetReleaseRequest = z.infer<typeof GetReleaseRequestSchema>;

export const GetTagRequestSchema = z.object({
  tag_id: z.string()
});
export type GetTagRequest = z.infer<typeof GetTagRequestSchema>;

export const HealthResponseSchema = z.object({
  status: z.string(),
  database: z.string()
});
export type HealthResponse = z.infer<typeof HealthResponseSchema>;

export const ImageUploadResponseSchema = z.object({
  blob_id: z.string(),
  job_id: z.string(),
  sha256: z.string(),
  size: z.number(),
  mime: z.string(),
  existing: z.boolean(),
  association: z.object({
  entity_type: z.string(),
  entity_id: z.string()
}).nullable(),
  message: z.string()
});
export type ImageUploadResponse = z.infer<typeof ImageUploadResponseSchema>;

export const JobSchema = z.object({
  id: z.string(),
  session_id: z.string().nullable(),
  job_type: z.string(),
  status: z.string(),
  parameters: z.string(),
  result: z.string().nullable(),
  retry_count: z.number(),
  max_retries: z.number(),
  scheduled_at: z.number(),
  started_at: z.number().nullable(),
  completed_at: z.number().nullable(),
  error_message: z.string().nullable(),
  created_by: z.string().nullable()
});
export type Job = z.infer<typeof JobSchema>;

export const ListFavoritesRequestSchema = z.object({
  user_id: z.string().nullable(),
  target_type: z.union([z.literal("song"), z.literal("artist"), z.literal("album"), z.literal("genre"), z.literal("playlist")]).nullable(),
  limit: z.number().nullable(),
  offset: z.number().nullable()
});
export type ListFavoritesRequest = z.infer<typeof ListFavoritesRequestSchema>;

export const ListFavoritesResponseSchema = z.object({
  favorites: z.array(z.union([z.literal('Song'), z.literal('Album'), z.literal('Artist'), z.literal('Playlist')])),
  total_count: z.number(),
  has_more: z.boolean(),
  offset: z.number(),
  limit: z.number()
});
export type ListFavoritesResponse = z.infer<typeof ListFavoritesResponseSchema>;

export const ListJobsRequestSchema = z.object({
  session_id: z.string().nullable(),
  status: z.string().nullable(),
  limit: z.number().nullable(),
  offset: z.number().nullable()
});
export type ListJobsRequest = z.infer<typeof ListJobsRequestSchema>;

export const ListeningHistoryItemSchema = z.object({
  id: z.string(),
  media_event_id: z.string(),
  song_id: z.string(),
  title: z.string(),
  artist: z.string().nullable(),
  album: z.string().nullable(),
  track_number: z.number().nullable(),
  disc_number: z.number().nullable(),
  duration: z.number().nullable(),
  genre: z.string().nullable(),
  playlist_id: z.string().nullable(),
  playlist_name: z.string().nullable(),
  user_id: z.string().nullable(),
  username: z.string().nullable(),
  session_id: z.string().nullable(),
  created_at: z.number(),
  event_data: z.any().nullable()
});
export type ListeningHistoryItem = z.infer<typeof ListeningHistoryItemSchema>;

export const ListeningHistoryRequestSchema = z.object({
  user_id: z.string().nullable(),
  limit: z.number().nullable(),
  offset: z.number().nullable()
});
export type ListeningHistoryRequest = z.infer<typeof ListeningHistoryRequestSchema>;

export const ListeningHistoryResponseSchema = z.object({
  items: z.array(z.object({
  id: z.string(),
  media_event_id: z.string(),
  song_id: z.string(),
  title: z.string(),
  artist: z.string().nullable(),
  album: z.string().nullable(),
  track_number: z.number().nullable(),
  disc_number: z.number().nullable(),
  duration: z.number().nullable(),
  genre: z.string().nullable(),
  playlist_id: z.string().nullable(),
  playlist_name: z.string().nullable(),
  user_id: z.string().nullable(),
  username: z.string().nullable(),
  session_id: z.string().nullable(),
  created_at: z.number(),
  event_data: z.any().nullable()
})),
  total: z.number()
});
export type ListeningHistoryResponse = z.infer<typeof ListeningHistoryResponseSchema>;

export const MediaBlobSchema = z.object({
  id: z.string(),
  sha256: z.string(),
  size: z.number().nullable(),
  mime: z.string().nullable(),
  source_client_id: z.string().nullable(),
  filename: z.string().nullable(),
  parent_blob_id: z.string().nullable(),
  blob_type: z.union([z.literal("original"), z.literal("thumbnail"), z.literal("waveform"), z.literal("preview")]),
  metadata: z.any(),
  created_at: z.number(),
  updated_at: z.number(),
  deleted_at: z.number().nullable(),
  deleted_by: z.string().nullable(),
  created_by: z.string().nullable(),
  updated_by: z.string().nullable()
});
export type MediaBlob = z.infer<typeof MediaBlobSchema>;

export const MusicMetadataHintsSchema = z.object({
  artist: z.string().nullable(),
  album: z.string().nullable(),
  title: z.string().nullable(),
  track_number: z.number().nullable(),
  disc_number: z.number().nullable(),
  year: z.number().nullable(),
  genre: z.string().nullable()
});
export type MusicMetadataHints = z.infer<typeof MusicMetadataHintsSchema>;

export const MusicUploadResponseSchema = z.object({
  blob_id: z.string(),
  job_id: z.string(),
  sha256: z.string(),
  size: z.number(),
  mime: z.string(),
  existing: z.boolean(),
  message: z.string()
});
export type MusicUploadResponse = z.infer<typeof MusicUploadResponseSchema>;

export const OverviewStatsSchema = z.object({
  total_songs: z.number(),
  total_albums: z.number(),
  total_artists: z.number(),
  total_users: z.number(),
  total_plays: z.number(),
  total_sessions: z.number(),
  total_favorites: z.number(),
  total_duration_seconds: z.number()
});
export type OverviewStats = z.infer<typeof OverviewStatsSchema>;

export const PlayAnalyticsSchema = z.object({
  song_id: z.string(),
  total_plays: z.number(),
  complete_plays: z.number(),
  partial_plays: z.number(),
  unique_users: z.number(),
  unique_sessions: z.number(),
  completion_rate: z.number(),
  avg_play_time_seconds: z.number(),
  total_play_time_seconds: z.number(),
  first_played_at: z.number().nullable(),
  last_played_at: z.number().nullable()
});
export type PlayAnalytics = z.infer<typeof PlayAnalyticsSchema>;

export const PlaylistSchema = z.object({
  id: z.string(),
  title: z.string(),
  description: z.string().nullable(),
  is_public: z.number(),
  images: z.array(z.object({
  blob_id: z.string(),
  is_primary: z.number(),
  blob_type: z.union([z.literal("original"), z.literal("thumbnail"), z.literal("waveform"), z.literal("preview")])
})).nullable(),
  urls: z.array(z.object({
  id: z.string().nullable(),
  name: z.string().nullable(),
  url: z.string()
})).nullable(),
  created_by_id: z.string().nullable(),
  created_at: z.number(),
  updated_at: z.number(),
  deleted_at: z.number().nullable(),
  deleted_by: z.string().nullable(),
  created_by: z.string().nullable(),
  updated_by: z.string().nullable(),
  song_count: z.number()
});
export type Playlist = z.infer<typeof PlaylistSchema>;

export const PlaylistQueryResultSchema = z.object({
  playlist: z.object({
  id: z.string(),
  title: z.string(),
  description: z.string().nullable(),
  is_public: z.number(),
  images: z.array(z.object({
  blob_id: z.string(),
  is_primary: z.number(),
  blob_type: z.union([z.literal("original"), z.literal("thumbnail"), z.literal("waveform"), z.literal("preview")])
})).nullable(),
  urls: z.array(z.object({
  id: z.string().nullable(),
  name: z.string().nullable(),
  url: z.string()
})).nullable(),
  created_by_id: z.string().nullable(),
  created_at: z.number(),
  updated_at: z.number(),
  deleted_at: z.number().nullable(),
  deleted_by: z.string().nullable(),
  created_by: z.string().nullable(),
  updated_by: z.string().nullable(),
  song_count: z.number()
}),
  song_count: z.number(),
  total_duration: z.number().nullable(),
  is_favorite: z.boolean().nullable()
});
export type PlaylistQueryResult = z.infer<typeof PlaylistQueryResultSchema>;

export const PlaylistSearchResultSchema = z.object({
  id: z.string(),
  title: z.string(),
  description: z.string().nullable(),
  song_count: z.number(),
  is_public: z.boolean(),
  created_by: z.string(),
  thumbnail_url: z.string().nullable(),
  search_rank: z.number(),
  highlight: z.string().nullable()
});
export type PlaylistSearchResult = z.infer<typeof PlaylistSearchResultSchema>;

export const PlaylistSongResultSchema = z.object({
  details: z.object({
  song: z.object({
  id: z.string(),
  media_blob_id: z.string(),
  images: z.array(z.object({
  blob_id: z.string(),
  is_primary: z.number(),
  blob_type: z.union([z.literal("original"), z.literal("thumbnail"), z.literal("waveform"), z.literal("preview")])
})).nullable(),
  urls: z.array(z.object({
  id: z.string().nullable(),
  name: z.string().nullable(),
  url: z.string()
})).nullable(),
  title: z.string(),
  track_number: z.number(),
  disc_number: z.number(),
  duration: z.number().nullable(),
  bpm: z.number().nullable(),
  track_artist: z.string().nullable(),
  metadata: z.string().nullable(),
  lyrics: z.string().nullable(),
  created_at: z.number(),
  updated_at: z.number(),
  deleted_at: z.number().nullable(),
  deleted_by: z.string().nullable(),
  created_by: z.string().nullable(),
  updated_by: z.string().nullable()
}),
  artist: z.object({
  id: z.string(),
  name: z.string(),
  bio: z.string().nullable(),
  images: z.array(z.object({
  blob_id: z.string(),
  is_primary: z.number(),
  blob_type: z.union([z.literal("original"), z.literal("thumbnail"), z.literal("waveform"), z.literal("preview")])
})).nullable(),
  urls: z.array(z.object({
  id: z.string().nullable(),
  name: z.string().nullable(),
  url: z.string()
})).nullable(),
  created_at: z.number(),
  updated_at: z.number(),
  deleted_at: z.number().nullable(),
  deleted_by: z.string().nullable(),
  created_by: z.string().nullable(),
  updated_by: z.string().nullable()
}).nullable(),
  album: z.object({
  id: z.string(),
  title: z.string(),
  album_type: z.string(),
  release_date: z.string().nullable(),
  label: z.string().nullable(),
  genres: z.array(z.object({
  id: z.string(),
  name: z.string()
})).nullable(),
  images: z.array(z.object({
  blob_id: z.string(),
  is_primary: z.number(),
  blob_type: z.union([z.literal("original"), z.literal("thumbnail"), z.literal("waveform"), z.literal("preview")])
})).nullable(),
  urls: z.array(z.object({
  id: z.string().nullable(),
  name: z.string().nullable(),
  url: z.string()
})).nullable(),
  song_count: z.number(),
  total_duration: z.number(),
  created_at: z.number(),
  updated_at: z.number(),
  deleted_at: z.number().nullable(),
  deleted_by: z.string().nullable(),
  created_by: z.string().nullable(),
  updated_by: z.string().nullable()
}).nullable(),
  genre: z.object({
  id: z.string(),
  name: z.string(),
  created_at: z.number()
}).nullable(),
  media_blob: z.object({
  id: z.string(),
  sha256: z.string(),
  size: z.number().nullable(),
  mime: z.string().nullable(),
  source_client_id: z.string().nullable(),
  filename: z.string().nullable(),
  parent_blob_id: z.string().nullable(),
  blob_type: z.union([z.literal("original"), z.literal("thumbnail"), z.literal("waveform"), z.literal("preview")]),
  metadata: z.any(),
  created_at: z.number(),
  updated_at: z.number(),
  deleted_at: z.number().nullable(),
  deleted_by: z.string().nullable(),
  created_by: z.string().nullable(),
  updated_by: z.string().nullable()
}).nullable(),
  images: z.array(z.object({
  blob_id: z.string(),
  is_primary: z.number(),
  blob_type: z.union([z.literal("original"), z.literal("thumbnail"), z.literal("waveform"), z.literal("preview")])
})).nullable(),
  relevance_score: z.number().nullable(),
  snippet: z.string().nullable(),
  is_favorite: z.boolean().nullable(),
  rating: z.number().nullable(),
  favorited_at: z.number().nullable(),
  rating_created_at: z.number().nullable(),
  artist_total_song_count: z.number().nullable(),
  artist_total_album_count: z.number().nullable(),
  artist_total_duration: z.number().nullable(),
  album_is_favorite: z.boolean().nullable(),
  album_rating: z.number().nullable(),
  album_tags: z.array(z.string()).nullable()
}),
  position: z.number(),
  added_at: z.number()
});
export type PlaylistSongResult = z.infer<typeof PlaylistSongResultSchema>;

export const PlaylistSongsQueryResultSchema = z.object({
  items: z.array(z.object({
  details: z.object({
  song: z.object({
  id: z.string(),
  media_blob_id: z.string(),
  images: z.array(z.object({
  blob_id: z.string(),
  is_primary: z.number(),
  blob_type: z.union([z.literal("original"), z.literal("thumbnail"), z.literal("waveform"), z.literal("preview")])
})).nullable(),
  urls: z.array(z.object({
  id: z.string().nullable(),
  name: z.string().nullable(),
  url: z.string()
})).nullable(),
  title: z.string(),
  track_number: z.number(),
  disc_number: z.number(),
  duration: z.number().nullable(),
  bpm: z.number().nullable(),
  track_artist: z.string().nullable(),
  metadata: z.string().nullable(),
  lyrics: z.string().nullable(),
  created_at: z.number(),
  updated_at: z.number(),
  deleted_at: z.number().nullable(),
  deleted_by: z.string().nullable(),
  created_by: z.string().nullable(),
  updated_by: z.string().nullable()
}),
  artist: z.object({
  id: z.string(),
  name: z.string(),
  bio: z.string().nullable(),
  images: z.array(z.object({
  blob_id: z.string(),
  is_primary: z.number(),
  blob_type: z.union([z.literal("original"), z.literal("thumbnail"), z.literal("waveform"), z.literal("preview")])
})).nullable(),
  urls: z.array(z.object({
  id: z.string().nullable(),
  name: z.string().nullable(),
  url: z.string()
})).nullable(),
  created_at: z.number(),
  updated_at: z.number(),
  deleted_at: z.number().nullable(),
  deleted_by: z.string().nullable(),
  created_by: z.string().nullable(),
  updated_by: z.string().nullable()
}).nullable(),
  album: z.object({
  id: z.string(),
  title: z.string(),
  album_type: z.string(),
  release_date: z.string().nullable(),
  label: z.string().nullable(),
  genres: z.array(z.object({
  id: z.string(),
  name: z.string()
})).nullable(),
  images: z.array(z.object({
  blob_id: z.string(),
  is_primary: z.number(),
  blob_type: z.union([z.literal("original"), z.literal("thumbnail"), z.literal("waveform"), z.literal("preview")])
})).nullable(),
  urls: z.array(z.object({
  id: z.string().nullable(),
  name: z.string().nullable(),
  url: z.string()
})).nullable(),
  song_count: z.number(),
  total_duration: z.number(),
  created_at: z.number(),
  updated_at: z.number(),
  deleted_at: z.number().nullable(),
  deleted_by: z.string().nullable(),
  created_by: z.string().nullable(),
  updated_by: z.string().nullable()
}).nullable(),
  genre: z.object({
  id: z.string(),
  name: z.string(),
  created_at: z.number()
}).nullable(),
  media_blob: z.object({
  id: z.string(),
  sha256: z.string(),
  size: z.number().nullable(),
  mime: z.string().nullable(),
  source_client_id: z.string().nullable(),
  filename: z.string().nullable(),
  parent_blob_id: z.string().nullable(),
  blob_type: z.union([z.literal("original"), z.literal("thumbnail"), z.literal("waveform"), z.literal("preview")]),
  metadata: z.any(),
  created_at: z.number(),
  updated_at: z.number(),
  deleted_at: z.number().nullable(),
  deleted_by: z.string().nullable(),
  created_by: z.string().nullable(),
  updated_by: z.string().nullable()
}).nullable(),
  images: z.array(z.object({
  blob_id: z.string(),
  is_primary: z.number(),
  blob_type: z.union([z.literal("original"), z.literal("thumbnail"), z.literal("waveform"), z.literal("preview")])
})).nullable(),
  relevance_score: z.number().nullable(),
  snippet: z.string().nullable(),
  is_favorite: z.boolean().nullable(),
  rating: z.number().nullable(),
  favorited_at: z.number().nullable(),
  rating_created_at: z.number().nullable(),
  artist_total_song_count: z.number().nullable(),
  artist_total_album_count: z.number().nullable(),
  artist_total_duration: z.number().nullable(),
  album_is_favorite: z.boolean().nullable(),
  album_rating: z.number().nullable(),
  album_tags: z.array(z.string()).nullable()
}),
  position: z.number(),
  added_at: z.number()
})),
  total_count: z.number(),
  has_more: z.boolean(),
  offset: z.number(),
  limit: z.number(),
  query_time_ms: z.number().nullable()
});
export type PlaylistSongsQueryResult = z.infer<typeof PlaylistSongsQueryResultSchema>;

export const PlaylistsQueryResultSchema = z.object({
  items: z.array(z.object({
  playlist: z.object({
  id: z.string(),
  title: z.string(),
  description: z.string().nullable(),
  is_public: z.number(),
  images: z.array(z.object({
  blob_id: z.string(),
  is_primary: z.number(),
  blob_type: z.union([z.literal("original"), z.literal("thumbnail"), z.literal("waveform"), z.literal("preview")])
})).nullable(),
  urls: z.array(z.object({
  id: z.string().nullable(),
  name: z.string().nullable(),
  url: z.string()
})).nullable(),
  created_by_id: z.string().nullable(),
  created_at: z.number(),
  updated_at: z.number(),
  deleted_at: z.number().nullable(),
  deleted_by: z.string().nullable(),
  created_by: z.string().nullable(),
  updated_by: z.string().nullable(),
  song_count: z.number()
}),
  song_count: z.number(),
  total_duration: z.number().nullable(),
  is_favorite: z.boolean().nullable()
})),
  total_count: z.number(),
  has_more: z.boolean(),
  offset: z.number(),
  limit: z.number(),
  query_time_ms: z.number().nullable()
});
export type PlaylistsQueryResult = z.infer<typeof PlaylistsQueryResultSchema>;

export const QueryContextSchema = z.object({
  tags: z.object({
  include: z.array(z.string()),
  exclude: z.array(z.string())
}).nullable(),
  sort_field: z.string().nullable(),
  sort_direction: z.union([z.literal("asc"), z.literal("desc")]).nullable(),
  search_query: z.string().nullable()
});
export type QueryContext = z.infer<typeof QueryContextSchema>;

export const QueryParamsSchema = z.object({
  q: z.string().nullable(),
  search_fields: z.array(z.string()).nullable(),
  filters: z.record(z.string(), z.any()),
  sort_by: z.string().nullable(),
  sort_direction: z.string().nullable(),
  limit: z.number().nullable(),
  offset: z.number().nullable(),
  user_id: z.string().nullable(),
  favorites_only: z.boolean().nullable(),
  min_rating: z.number().nullable()
});
export type QueryParams = z.infer<typeof QueryParamsSchema>;

export const QueryPlaylistSongsRequestSchema = z.object({
  playlist_id: z.string(),
  q: z.string().nullable(),
  sort_by: z.string().nullable(),
  sort_direction: z.string().nullable(),
  limit: z.number().nullable(),
  offset: z.number().nullable()
});
export type QueryPlaylistSongsRequest = z.infer<typeof QueryPlaylistSongsRequestSchema>;

export const QueryTagsRequestSchema = z.object({
  search: z.string().nullable()
});
export type QueryTagsRequest = z.infer<typeof QueryTagsRequestSchema>;

export const RatingStatsSchema = z.object({
  average_rating: z.number(),
  total_ratings: z.number()
});
export type RatingStats = z.infer<typeof RatingStatsSchema>;

export const RecentSongsRequestSchema = z.object({
  limit: z.number().nullable()
});
export type RecentSongsRequest = z.infer<typeof RecentSongsRequestSchema>;

export const RecordPlayRequestSchema = z.object({
  media_blob_id: z.string(),
  song_id: z.string(),
  session_id: z.string().nullable(),
  event_data: z.any().nullable()
});
export type RecordPlayRequest = z.infer<typeof RecordPlayRequestSchema>;

export const RedeemInviteRequestSchema = z.object({
  invite_code: z.string(),
  username: z.string()
});
export type RedeemInviteRequest = z.infer<typeof RedeemInviteRequestSchema>;

export const RegisterStartRequestSchema = z.object({
  username: z.string(),
  invite_code: z.string().nullable()
});
export type RegisterStartRequest = z.infer<typeof RegisterStartRequestSchema>;

export const RemoveAlbumsTagsRequestSchema = z.object({
  album_ids: z.array(z.string()),
  tag_ids: z.array(z.string())
});
export type RemoveAlbumsTagsRequest = z.infer<typeof RemoveAlbumsTagsRequestSchema>;

export const RemovePlaylistThumbnailRequestSchema = z.object({
  playlist_id: z.string(),
  cleanup_blob: z.boolean().nullable(),
  deleted_by: z.string().nullable()
});
export type RemovePlaylistThumbnailRequest = z.infer<typeof RemovePlaylistThumbnailRequestSchema>;

export const RemoveRatingRequestSchema = z.object({
  user_id: z.string().nullable(),
  target_type: z.union([z.literal("song"), z.literal("artist"), z.literal("album")]),
  target_id: z.string()
});
export type RemoveRatingRequest = z.infer<typeof RemoveRatingRequestSchema>;

export const RemoveRatingResponseSchema = z.object({
  success: z.boolean(),
  message: z.string()
});
export type RemoveRatingResponse = z.infer<typeof RemoveRatingResponseSchema>;

export const RemoveSongsFromPlaylistRequestSchema = z.object({
  playlist_id: z.string(),
  song_ids: z.array(z.string())
});
export type RemoveSongsFromPlaylistRequest = z.infer<typeof RemoveSongsFromPlaylistRequestSchema>;

export const ReorderPlaylistSongsRequestSchema = z.object({
  playlist_id: z.string(),
  song_ids: z.array(z.string()),
  new_position: z.number()
});
export type ReorderPlaylistSongsRequest = z.infer<typeof ReorderPlaylistSongsRequestSchema>;

export const ReplaceAlbumsTagsRequestSchema = z.object({
  album_ids: z.array(z.string()),
  tag_ids: z.array(z.string())
});
export type ReplaceAlbumsTagsRequest = z.infer<typeof ReplaceAlbumsTagsRequestSchema>;

export const SearchFieldSchema = z.union([z.literal("all"), z.literal("artists"), z.literal("albums"), z.literal("songs"), z.literal("genres"), z.literal("playlists")]);
export type SearchField = z.infer<typeof SearchFieldSchema>;

export const SearchRecordingsRequestSchema = z.object({
  query: z.string(),
  artist: z.string().nullable(),
  recording: z.string().nullable(),
  limit: z.number().nullable(),
  offset: z.number().nullable()
});
export type SearchRecordingsRequest = z.infer<typeof SearchRecordingsRequestSchema>;

export const SearchReleasesRequestSchema = z.object({
  query: z.string(),
  artist: z.string().nullable(),
  release: z.string().nullable(),
  limit: z.number().nullable(),
  offset: z.number().nullable()
});
export type SearchReleasesRequest = z.infer<typeof SearchReleasesRequestSchema>;

export const SearchRequestSchema = z.object({
  query: z.string(),
  field: z.union([z.literal("all"), z.literal("artists"), z.literal("albums"), z.literal("songs"), z.literal("genres"), z.literal("playlists")]).nullable(),
  page: z.number().nullable(),
  page_size: z.number().nullable(),
  context: z.object({
  tags: z.object({
  include: z.array(z.string()),
  exclude: z.array(z.string())
}).nullable(),
  sort_field: z.string().nullable(),
  sort_direction: z.union([z.literal("asc"), z.literal("desc")]).nullable(),
  search_query: z.string().nullable()
}).nullable()
});
export type SearchRequest = z.infer<typeof SearchRequestSchema>;

export const SearchResponseSchema = z.object({
  songs: z.array(z.object({
  id: z.string(),
  title: z.string(),
  artist_names: z.array(z.string()),
  album_title: z.string().nullable(),
  album_id: z.string().nullable(),
  duration: z.number().nullable(),
  thumbnail_url: z.string().nullable(),
  user_rating: z.number().nullable(),
  is_favorite: z.boolean(),
  search_rank: z.number(),
  match_type: z.string(),
  highlight: z.string().nullable()
})),
  artists: z.array(z.object({
  id: z.string(),
  name: z.string(),
  song_count: z.number(),
  album_count: z.number(),
  genres: z.array(z.string()),
  user_rating: z.number().nullable(),
  is_favorite: z.boolean(),
  search_rank: z.number(),
  highlight: z.string().nullable()
})).nullable(),
  albums: z.array(z.object({
  id: z.string(),
  title: z.string(),
  artist_names: z.array(z.string()),
  genres: z.array(z.string()),
  song_count: z.number(),
  thumbnail_url: z.string().nullable(),
  user_rating: z.number().nullable(),
  is_favorite: z.boolean(),
  search_rank: z.number(),
  highlight: z.string().nullable()
})).nullable(),
  genres: z.array(z.object({
  genre: z.string(),
  genre_id: z.string(),
  song_count: z.number(),
  artist_count: z.number(),
  representative_song_id: z.string().nullable(),
  representative_thumbnail: z.string().nullable(),
  avg_rating: z.number().nullable(),
  search_rank: z.number()
})).nullable(),
  playlists: z.array(z.object({
  id: z.string(),
  title: z.string(),
  description: z.string().nullable(),
  song_count: z.number(),
  is_public: z.boolean(),
  created_by: z.string(),
  thumbnail_url: z.string().nullable(),
  search_rank: z.number(),
  highlight: z.string().nullable()
})).nullable(),
  total_count: z.number(),
  page: z.number(),
  page_size: z.number(),
  total_pages: z.number(),
  has_next: z.boolean(),
  has_prev: z.boolean(),
  query_time_ms: z.number(),
  applied_filters: z.any().nullable(),
  sort_applied: z.string().nullable()
});
export type SearchResponse = z.infer<typeof SearchResponseSchema>;

export const ServerInfoResponseSchema = z.object({
  server_id: z.string(),
  name: z.string(),
  description: z.string().nullable(),
  version: z.string(),
  image_url: z.string().nullable()
});
export type ServerInfoResponse = z.infer<typeof ServerInfoResponseSchema>;

export const SessionSongSchema = z.object({
  song_id: z.string(),
  title: z.string(),
  artist: z.string().nullable(),
  album: z.string().nullable(),
  images: z.array(z.object({
  blob_id: z.string(),
  is_primary: z.number(),
  blob_type: z.union([z.literal("original"), z.literal("thumbnail"), z.literal("waveform"), z.literal("preview")])
})).nullable(),
  played_at: z.number()
});
export type SessionSong = z.infer<typeof SessionSongSchema>;

export const SessionSummarySchema = z.object({
  session_id: z.string(),
  user_id: z.string().nullable(),
  username: z.string().nullable(),
  songs: z.array(z.object({
  song_id: z.string(),
  title: z.string(),
  artist: z.string().nullable(),
  album: z.string().nullable(),
  images: z.array(z.object({
  blob_id: z.string(),
  is_primary: z.number(),
  blob_type: z.union([z.literal("original"), z.literal("thumbnail"), z.literal("waveform"), z.literal("preview")])
})).nullable(),
  played_at: z.number()
})),
  total_duration: z.number(),
  session_start: z.number(),
  session_end: z.number(),
  song_count: z.number()
});
export type SessionSummary = z.infer<typeof SessionSummarySchema>;

export const SetFavoriteRequestSchema = z.object({
  user_id: z.string().nullable(),
  target_type: z.union([z.literal("song"), z.literal("artist"), z.literal("album"), z.literal("genre"), z.literal("playlist")]),
  target_id: z.string(),
  is_favorite: z.boolean()
});
export type SetFavoriteRequest = z.infer<typeof SetFavoriteRequestSchema>;

export const SetFavoriteResponseSchema = z.object({
  success: z.boolean(),
  message: z.string()
});
export type SetFavoriteResponse = z.infer<typeof SetFavoriteResponseSchema>;

export const SetPrimaryImageRequestSchema = z.object({
  entity_type: z.string(),
  entity_id: z.string(),
  blob_id: z.string()
});
export type SetPrimaryImageRequest = z.infer<typeof SetPrimaryImageRequestSchema>;

export const SetRatingRequestSchema = z.object({
  user_id: z.string().nullable(),
  target_type: z.union([z.literal("song"), z.literal("artist"), z.literal("album")]),
  target_id: z.string(),
  rating: z.number()
});
export type SetRatingRequest = z.infer<typeof SetRatingRequestSchema>;

export const SetRatingResponseSchema = z.object({
  success: z.boolean(),
  message: z.string()
});
export type SetRatingResponse = z.infer<typeof SetRatingResponseSchema>;

export const SongSchema = z.object({
  id: z.string(),
  media_blob_id: z.string(),
  images: z.array(z.object({
  blob_id: z.string(),
  is_primary: z.number(),
  blob_type: z.union([z.literal("original"), z.literal("thumbnail"), z.literal("waveform"), z.literal("preview")])
})).nullable(),
  urls: z.array(z.object({
  id: z.string().nullable(),
  name: z.string().nullable(),
  url: z.string()
})).nullable(),
  title: z.string(),
  track_number: z.number(),
  disc_number: z.number(),
  duration: z.number().nullable(),
  bpm: z.number().nullable(),
  track_artist: z.string().nullable(),
  metadata: z.string().nullable(),
  lyrics: z.string().nullable(),
  created_at: z.number(),
  updated_at: z.number(),
  deleted_at: z.number().nullable(),
  deleted_by: z.string().nullable(),
  created_by: z.string().nullable(),
  updated_by: z.string().nullable()
});
export type Song = z.infer<typeof SongSchema>;

export const SongAnalyticsRequestSchema = z.object({
  song_id: z.string()
});
export type SongAnalyticsRequest = z.infer<typeof SongAnalyticsRequestSchema>;

export const SongQueryResultSchema = z.object({
  song: z.object({
  id: z.string(),
  media_blob_id: z.string(),
  images: z.array(z.object({
  blob_id: z.string(),
  is_primary: z.number(),
  blob_type: z.union([z.literal("original"), z.literal("thumbnail"), z.literal("waveform"), z.literal("preview")])
})).nullable(),
  urls: z.array(z.object({
  id: z.string().nullable(),
  name: z.string().nullable(),
  url: z.string()
})).nullable(),
  title: z.string(),
  track_number: z.number(),
  disc_number: z.number(),
  duration: z.number().nullable(),
  bpm: z.number().nullable(),
  track_artist: z.string().nullable(),
  metadata: z.string().nullable(),
  lyrics: z.string().nullable(),
  created_at: z.number(),
  updated_at: z.number(),
  deleted_at: z.number().nullable(),
  deleted_by: z.string().nullable(),
  created_by: z.string().nullable(),
  updated_by: z.string().nullable()
}),
  artist: z.object({
  id: z.string(),
  name: z.string(),
  bio: z.string().nullable(),
  images: z.array(z.object({
  blob_id: z.string(),
  is_primary: z.number(),
  blob_type: z.union([z.literal("original"), z.literal("thumbnail"), z.literal("waveform"), z.literal("preview")])
})).nullable(),
  urls: z.array(z.object({
  id: z.string().nullable(),
  name: z.string().nullable(),
  url: z.string()
})).nullable(),
  created_at: z.number(),
  updated_at: z.number(),
  deleted_at: z.number().nullable(),
  deleted_by: z.string().nullable(),
  created_by: z.string().nullable(),
  updated_by: z.string().nullable()
}).nullable(),
  album: z.object({
  id: z.string(),
  title: z.string(),
  album_type: z.string(),
  release_date: z.string().nullable(),
  label: z.string().nullable(),
  genres: z.array(z.object({
  id: z.string(),
  name: z.string()
})).nullable(),
  images: z.array(z.object({
  blob_id: z.string(),
  is_primary: z.number(),
  blob_type: z.union([z.literal("original"), z.literal("thumbnail"), z.literal("waveform"), z.literal("preview")])
})).nullable(),
  urls: z.array(z.object({
  id: z.string().nullable(),
  name: z.string().nullable(),
  url: z.string()
})).nullable(),
  song_count: z.number(),
  total_duration: z.number(),
  created_at: z.number(),
  updated_at: z.number(),
  deleted_at: z.number().nullable(),
  deleted_by: z.string().nullable(),
  created_by: z.string().nullable(),
  updated_by: z.string().nullable()
}).nullable(),
  genre: z.object({
  id: z.string(),
  name: z.string(),
  created_at: z.number()
}).nullable(),
  media_blob: z.object({
  id: z.string(),
  sha256: z.string(),
  size: z.number().nullable(),
  mime: z.string().nullable(),
  source_client_id: z.string().nullable(),
  filename: z.string().nullable(),
  parent_blob_id: z.string().nullable(),
  blob_type: z.union([z.literal("original"), z.literal("thumbnail"), z.literal("waveform"), z.literal("preview")]),
  metadata: z.any(),
  created_at: z.number(),
  updated_at: z.number(),
  deleted_at: z.number().nullable(),
  deleted_by: z.string().nullable(),
  created_by: z.string().nullable(),
  updated_by: z.string().nullable()
}).nullable(),
  images: z.array(z.object({
  blob_id: z.string(),
  is_primary: z.number(),
  blob_type: z.union([z.literal("original"), z.literal("thumbnail"), z.literal("waveform"), z.literal("preview")])
})).nullable(),
  relevance_score: z.number().nullable(),
  snippet: z.string().nullable(),
  is_favorite: z.boolean().nullable(),
  rating: z.number().nullable(),
  favorited_at: z.number().nullable(),
  rating_created_at: z.number().nullable(),
  artist_total_song_count: z.number().nullable(),
  artist_total_album_count: z.number().nullable(),
  artist_total_duration: z.number().nullable(),
  album_is_favorite: z.boolean().nullable(),
  album_rating: z.number().nullable(),
  album_tags: z.array(z.string()).nullable()
});
export type SongQueryResult = z.infer<typeof SongQueryResultSchema>;

export const SongSearchResultSchema = z.object({
  id: z.string(),
  title: z.string(),
  artist_names: z.array(z.string()),
  album_title: z.string().nullable(),
  album_id: z.string().nullable(),
  duration: z.number().nullable(),
  thumbnail_url: z.string().nullable(),
  user_rating: z.number().nullable(),
  is_favorite: z.boolean(),
  search_rank: z.number(),
  match_type: z.string(),
  highlight: z.string().nullable()
});
export type SongSearchResult = z.infer<typeof SongSearchResultSchema>;

export const SongUpdateErrorSchema = z.object({
  song_id: z.string(),
  error_message: z.string()
});
export type SongUpdateError = z.infer<typeof SongUpdateErrorSchema>;

export const SongsQueryResultSchema = z.object({
  items: z.array(z.object({
  song: z.object({
  id: z.string(),
  media_blob_id: z.string(),
  images: z.array(z.object({
  blob_id: z.string(),
  is_primary: z.number(),
  blob_type: z.union([z.literal("original"), z.literal("thumbnail"), z.literal("waveform"), z.literal("preview")])
})).nullable(),
  urls: z.array(z.object({
  id: z.string().nullable(),
  name: z.string().nullable(),
  url: z.string()
})).nullable(),
  title: z.string(),
  track_number: z.number(),
  disc_number: z.number(),
  duration: z.number().nullable(),
  bpm: z.number().nullable(),
  track_artist: z.string().nullable(),
  metadata: z.string().nullable(),
  lyrics: z.string().nullable(),
  created_at: z.number(),
  updated_at: z.number(),
  deleted_at: z.number().nullable(),
  deleted_by: z.string().nullable(),
  created_by: z.string().nullable(),
  updated_by: z.string().nullable()
}),
  artist: z.object({
  id: z.string(),
  name: z.string(),
  bio: z.string().nullable(),
  images: z.array(z.object({
  blob_id: z.string(),
  is_primary: z.number(),
  blob_type: z.union([z.literal("original"), z.literal("thumbnail"), z.literal("waveform"), z.literal("preview")])
})).nullable(),
  urls: z.array(z.object({
  id: z.string().nullable(),
  name: z.string().nullable(),
  url: z.string()
})).nullable(),
  created_at: z.number(),
  updated_at: z.number(),
  deleted_at: z.number().nullable(),
  deleted_by: z.string().nullable(),
  created_by: z.string().nullable(),
  updated_by: z.string().nullable()
}).nullable(),
  album: z.object({
  id: z.string(),
  title: z.string(),
  album_type: z.string(),
  release_date: z.string().nullable(),
  label: z.string().nullable(),
  genres: z.array(z.object({
  id: z.string(),
  name: z.string()
})).nullable(),
  images: z.array(z.object({
  blob_id: z.string(),
  is_primary: z.number(),
  blob_type: z.union([z.literal("original"), z.literal("thumbnail"), z.literal("waveform"), z.literal("preview")])
})).nullable(),
  urls: z.array(z.object({
  id: z.string().nullable(),
  name: z.string().nullable(),
  url: z.string()
})).nullable(),
  song_count: z.number(),
  total_duration: z.number(),
  created_at: z.number(),
  updated_at: z.number(),
  deleted_at: z.number().nullable(),
  deleted_by: z.string().nullable(),
  created_by: z.string().nullable(),
  updated_by: z.string().nullable()
}).nullable(),
  genre: z.object({
  id: z.string(),
  name: z.string(),
  created_at: z.number()
}).nullable(),
  media_blob: z.object({
  id: z.string(),
  sha256: z.string(),
  size: z.number().nullable(),
  mime: z.string().nullable(),
  source_client_id: z.string().nullable(),
  filename: z.string().nullable(),
  parent_blob_id: z.string().nullable(),
  blob_type: z.union([z.literal("original"), z.literal("thumbnail"), z.literal("waveform"), z.literal("preview")]),
  metadata: z.any(),
  created_at: z.number(),
  updated_at: z.number(),
  deleted_at: z.number().nullable(),
  deleted_by: z.string().nullable(),
  created_by: z.string().nullable(),
  updated_by: z.string().nullable()
}).nullable(),
  images: z.array(z.object({
  blob_id: z.string(),
  is_primary: z.number(),
  blob_type: z.union([z.literal("original"), z.literal("thumbnail"), z.literal("waveform"), z.literal("preview")])
})).nullable(),
  relevance_score: z.number().nullable(),
  snippet: z.string().nullable(),
  is_favorite: z.boolean().nullable(),
  rating: z.number().nullable(),
  favorited_at: z.number().nullable(),
  rating_created_at: z.number().nullable(),
  artist_total_song_count: z.number().nullable(),
  artist_total_album_count: z.number().nullable(),
  artist_total_duration: z.number().nullable(),
  album_is_favorite: z.boolean().nullable(),
  album_rating: z.number().nullable(),
  album_tags: z.array(z.string()).nullable()
})),
  total_count: z.number(),
  has_more: z.boolean(),
  offset: z.number(),
  limit: z.number(),
  query_time_ms: z.number().nullable()
});
export type SongsQueryResult = z.infer<typeof SongsQueryResultSchema>;

export const StartLoginRequestSchema = z.object({
  username: z.string()
});
export type StartLoginRequest = z.infer<typeof StartLoginRequestSchema>;

export const SuggestionSchema = z.object({
  value: z.string(),
  display: z.string(),
  highlight: z.string(),
  count: z.number(),
  suggestion_type: z.union([z.literal("artist"), z.literal("album"), z.literal("song"), z.literal("genre"), z.literal("playlist")]),
  confidence: z.number(),
  metadata: z.any().nullable(),
  entity_id: z.string(),
  is_favorite: z.boolean()
});
export type Suggestion = z.infer<typeof SuggestionSchema>;

export const SuggestionTypeSchema = z.union([z.literal("artist"), z.literal("album"), z.literal("song"), z.literal("genre"), z.literal("playlist")]);
export type SuggestionType = z.infer<typeof SuggestionTypeSchema>;

export const SuggestionsRequestSchema = z.object({
  field: z.union([z.literal("all"), z.literal("artists"), z.literal("albums"), z.literal("songs"), z.literal("genres"), z.literal("playlists")]),
  partial: z.string(),
  page: z.number().nullable(),
  page_size: z.number().nullable(),
  context: z.object({
  tags: z.object({
  include: z.array(z.string()),
  exclude: z.array(z.string())
}).nullable(),
  sort_field: z.string().nullable(),
  sort_direction: z.union([z.literal("asc"), z.literal("desc")]).nullable(),
  search_query: z.string().nullable()
}).nullable()
});
export type SuggestionsRequest = z.infer<typeof SuggestionsRequestSchema>;

export const SuggestionsResponseSchema = z.object({
  suggestions: z.array(z.object({
  value: z.string(),
  display: z.string(),
  highlight: z.string(),
  count: z.number(),
  suggestion_type: z.union([z.literal("artist"), z.literal("album"), z.literal("song"), z.literal("genre"), z.literal("playlist")]),
  confidence: z.number(),
  metadata: z.any().nullable(),
  entity_id: z.string(),
  is_favorite: z.boolean()
})),
  query_time_ms: z.number(),
  total_count: z.number(),
  page: z.number(),
  page_size: z.number(),
  total_pages: z.number(),
  has_next: z.boolean(),
  has_prev: z.boolean()
});
export type SuggestionsResponse = z.infer<typeof SuggestionsResponseSchema>;

export const TagSchema = z.object({
  id: z.string(),
  name: z.string(),
  created_at: z.number()
});
export type Tag = z.infer<typeof TagSchema>;

export const TopAlbumSchema = z.object({
  album_id: z.string(),
  title: z.string(),
  artist_name: z.string().nullable(),
  images: z.array(z.object({
  blob_id: z.string(),
  is_primary: z.number(),
  blob_type: z.union([z.literal("original"), z.literal("thumbnail"), z.literal("waveform"), z.literal("preview")])
})).nullable(),
  total_plays: z.number(),
  song_count: z.number(),
  unique_users: z.number()
});
export type TopAlbum = z.infer<typeof TopAlbumSchema>;

export const TopAlbumsRequestSchema = z.object({
  limit: z.number().nullable(),
  days: z.number().nullable()
});
export type TopAlbumsRequest = z.infer<typeof TopAlbumsRequestSchema>;

export const TopArtistSchema = z.object({
  artist_id: z.string(),
  name: z.string(),
  total_plays: z.number(),
  song_count: z.number(),
  album_count: z.number(),
  unique_users: z.number()
});
export type TopArtist = z.infer<typeof TopArtistSchema>;

export const TopArtistsRequestSchema = z.object({
  limit: z.number().nullable(),
  days: z.number().nullable()
});
export type TopArtistsRequest = z.infer<typeof TopArtistsRequestSchema>;

export const TopSongSchema = z.object({
  song_id: z.string(),
  title: z.string(),
  artist_name: z.string().nullable(),
  album_title: z.string().nullable(),
  images: z.array(z.object({
  blob_id: z.string(),
  is_primary: z.number(),
  blob_type: z.union([z.literal("original"), z.literal("thumbnail"), z.literal("waveform"), z.literal("preview")])
})).nullable(),
  play_count: z.number(),
  unique_users: z.number(),
  last_played_at: z.number().nullable()
});
export type TopSong = z.infer<typeof TopSongSchema>;

export const TopSongsRequestSchema = z.object({
  limit: z.number().nullable(),
  days: z.number().nullable()
});
export type TopSongsRequest = z.infer<typeof TopSongsRequestSchema>;

export const UpdateAlbumRequestSchema = z.object({
  album_id: z.string(),
  title: z.string().nullable(),
  artist_id: z.string().nullable(),
  artist_name: z.string().nullable(),
  album_type: z.string().nullable(),
  release_date: z.string().nullable(),
  label: z.string().nullable(),
  genre_ids: z.array(z.string()).nullable(),
  genres: z.array(z.string()).nullable(),
  entity_urls: z.array(z.object({
  id: z.string().nullable(),
  name: z.string().nullable(),
  url: z.string()
})).nullable(),
  updated_by: z.string().nullable()
});
export type UpdateAlbumRequest = z.infer<typeof UpdateAlbumRequestSchema>;

export const UpdateArtistRequestSchema = z.object({
  artist_id: z.string(),
  name: z.string().nullable(),
  bio: z.string().nullable(),
  entity_urls: z.array(z.object({
  id: z.string().nullable(),
  name: z.string().nullable(),
  url: z.string()
})).nullable(),
  updated_by: z.string().nullable()
});
export type UpdateArtistRequest = z.infer<typeof UpdateArtistRequestSchema>;

export const UpdatePlaylistRequestSchema = z.object({
  playlist_id: z.string(),
  title: z.string().nullable(),
  description: z.string().nullable(),
  is_public: z.boolean().nullable(),
  entity_urls: z.array(z.object({
  id: z.string().nullable(),
  name: z.string().nullable(),
  url: z.string()
})).nullable(),
  updated_by: z.string().nullable()
});
export type UpdatePlaylistRequest = z.infer<typeof UpdatePlaylistRequestSchema>;

export const UpdateSongsRequestSchema = z.object({
  song_ids: z.array(z.string()),
  user_id: z.string().nullable(),
  updated_by: z.string().nullable(),
  title: z.string().nullable(),
  track_number: z.number().nullable(),
  disc_number: z.number().nullable(),
  duration: z.number().nullable(),
  year: z.number().nullable(),
  bpm: z.number().nullable(),
  lyrics: z.string().nullable(),
  metadata: z.string().nullable(),
  artist: z.object({
  name: z.string()
}).nullable(),
  artist_name: z.string().nullable(),
  album: z.object({
  title: z.string(),
  album_type: z.string().nullable(),
  release_date: z.string().nullable(),
  label: z.string().nullable()
}).nullable(),
  album_title: z.string().nullable(),
  album_type: z.string().nullable(),
  release_date: z.string().nullable(),
  label: z.string().nullable(),
  genre: z.string().nullable(),
  sub_genre: z.string().nullable(),
  add_tags: z.array(z.string()).nullable(),
  remove_tags: z.array(z.string()).nullable(),
  replace_tags: z.array(z.string()).nullable(),
  set_favorite: z.object({
  target_type: z.union([z.literal("song"), z.literal("artist"), z.literal("album")]),
  is_favorite: z.boolean()
}).nullable(),
  favorite_song: z.boolean().nullable(),
  favorite_artist: z.boolean().nullable(),
  favorite_album: z.boolean().nullable(),
  set_rating: z.object({
  target_type: z.union([z.literal("song"), z.literal("artist"), z.literal("album")]),
  rating: z.number()
}).nullable(),
  rate_song: z.number().nullable(),
  rate_artist: z.number().nullable(),
  rate_album: z.number().nullable(),
  entity_urls: z.array(z.object({
  id: z.string().nullable(),
  name: z.string().nullable(),
  url: z.string()
})).nullable()
});
export type UpdateSongsRequest = z.infer<typeof UpdateSongsRequestSchema>;

export const UpdateSongsResultSchema = z.object({
  songs_updated: z.number(),
  songs_failed: z.array(z.object({
  song_id: z.string(),
  error_message: z.string()
})),
  artist: z.object({
  id: z.string(),
  name: z.string(),
  bio: z.string().nullable(),
  images: z.array(z.object({
  blob_id: z.string(),
  is_primary: z.number(),
  blob_type: z.union([z.literal("original"), z.literal("thumbnail"), z.literal("waveform"), z.literal("preview")])
})).nullable(),
  urls: z.array(z.object({
  id: z.string().nullable(),
  name: z.string().nullable(),
  url: z.string()
})).nullable(),
  created_at: z.number(),
  updated_at: z.number(),
  deleted_at: z.number().nullable(),
  deleted_by: z.string().nullable(),
  created_by: z.string().nullable(),
  updated_by: z.string().nullable()
}).nullable(),
  album: z.object({
  id: z.string(),
  title: z.string(),
  album_type: z.string(),
  release_date: z.string().nullable(),
  label: z.string().nullable(),
  genres: z.array(z.object({
  id: z.string(),
  name: z.string()
})).nullable(),
  images: z.array(z.object({
  blob_id: z.string(),
  is_primary: z.number(),
  blob_type: z.union([z.literal("original"), z.literal("thumbnail"), z.literal("waveform"), z.literal("preview")])
})).nullable(),
  urls: z.array(z.object({
  id: z.string().nullable(),
  name: z.string().nullable(),
  url: z.string()
})).nullable(),
  song_count: z.number(),
  total_duration: z.number(),
  created_at: z.number(),
  updated_at: z.number(),
  deleted_at: z.number().nullable(),
  deleted_by: z.string().nullable(),
  created_by: z.string().nullable(),
  updated_by: z.string().nullable()
}).nullable(),
  genre: z.object({
  id: z.string(),
  name: z.string(),
  created_at: z.number()
}).nullable(),
  tags_modified: z.boolean()
});
export type UpdateSongsResult = z.infer<typeof UpdateSongsResultSchema>;

export const UserStatsSchema = z.object({
  user_id: z.string(),
  username: z.string(),
  total_plays: z.number(),
  unique_songs_played: z.number(),
  unique_sessions: z.number(),
  total_favorites: z.number(),
  first_activity_at: z.number().nullable(),
  last_activity_at: z.number().nullable()
});
export type UserStats = z.infer<typeof UserStatsSchema>;

export const WhoAmIResponseSchema = z.object({
  user_id: z.string(),
  username: z.string(),
  role: z.string()
});
export type WhoAmIResponse = z.infer<typeof WhoAmIResponseSchema>;

