// Automatically generated by zod_gen
import * as z from 'zod';

export const ApiKeyRegenerateResponseSchema = z.object({
  api_key: z.string(),
  message: z.string()
});
export type ApiKeyRegenerateResponse = z.infer<typeof ApiKeyRegenerateResponseSchema>;

export const ApiKeyStatusResponseSchema = z.object({
  has_api_key: z.boolean(),
  api_key_preview: z.string().nullable()
});
export type ApiKeyStatusResponse = z.infer<typeof ApiKeyStatusResponseSchema>;

export const ArtistSchema = z.object({
  id: z.string(),
  name: z.string(),
  created_at: z.number(),
  updated_at: z.number(),
  deleted_at: z.number().nullable(),
  deleted_by: z.string().nullable(),
  created_by: z.string().nullable(),
  updated_by: z.string().nullable()
});
export type Artist = z.infer<typeof ArtistSchema>;

export const CreateArtistRequestSchema = z.object({
  name: z.string(),
  created_by: z.string().nullable()
});
export type CreateArtistRequest = z.infer<typeof CreateArtistRequestSchema>;

export const CreateJobRequestSchema = z.object({
  job_type: z.union([z.literal('ScanDirectory'), z.literal('ProcessFile'), z.literal('ExtractMetadata'), z.literal('GenerateThumbnail'), z.literal('GenerateWaveform'), z.literal('FetchMedia')]),
  session_id: z.string().nullable(),
  parameters: z.any(),
  max_retries: z.number().nullable(),
  scheduled_at: z.number().nullable(),
  created_by: z.string().nullable()
});
export type CreateJobRequest = z.infer<typeof CreateJobRequestSchema>;

export const CreatePlaylistRequestSchema = z.object({
  title: z.string().nullable(),
  description: z.string().nullable(),
  is_public: z.boolean().nullable(),
  created_by_id: z.string().nullable()
});
export type CreatePlaylistRequest = z.infer<typeof CreatePlaylistRequestSchema>;

export const FetchMediaParamsSchema = z.object({
  url: z.string(),
  user_id: z.string().nullable()
});
export type FetchMediaParams = z.infer<typeof FetchMediaParamsSchema>;

export const FetchMediaResultSchema = z.object({
  items_requested: z.number(),
  items_downloaded: z.number(),
  items_failed: z.number(),
  media_blob_ids: z.array(z.string()),
  song_ids: z.array(z.string()),
  errors: z.array(z.string())
});
export type FetchMediaResult = z.infer<typeof FetchMediaResultSchema>;

export const JobSchema = z.object({
  id: z.string(),
  session_id: z.string().nullable(),
  job_type: z.string(),
  status: z.string(),
  parameters: z.string(),
  result: z.string().nullable(),
  retry_count: z.number(),
  max_retries: z.number(),
  scheduled_at: z.number(),
  started_at: z.number().nullable(),
  completed_at: z.number().nullable(),
  error_message: z.string().nullable(),
  created_by: z.string().nullable()
});
export type Job = z.infer<typeof JobSchema>;

export const PlaylistSchema = z.object({
  id: z.string(),
  title: z.string(),
  description: z.string().nullable(),
  is_public: z.number(),
  thumbnail_blob_id: z.string().nullable(),
  created_by_id: z.string().nullable(),
  created_at: z.number(),
  updated_at: z.number(),
  deleted_at: z.number().nullable(),
  deleted_by: z.string().nullable(),
  created_by: z.string().nullable(),
  updated_by: z.string().nullable(),
  song_count: z.number()
});
export type Playlist = z.infer<typeof PlaylistSchema>;

export const PlaylistQueryResultSchema = z.object({
  playlist: z.object({
  id: z.string(),
  title: z.string(),
  description: z.string().nullable(),
  is_public: z.number(),
  thumbnail_blob_id: z.string().nullable(),
  created_by_id: z.string().nullable(),
  created_at: z.number(),
  updated_at: z.number(),
  deleted_at: z.number().nullable(),
  deleted_by: z.string().nullable(),
  created_by: z.string().nullable(),
  updated_by: z.string().nullable(),
  song_count: z.number()
}),
  song_count: z.number(),
  total_duration: z.number().nullable(),
  is_favorite: z.boolean().nullable()
});
export type PlaylistQueryResult = z.infer<typeof PlaylistQueryResultSchema>;

export const QueryParamsSchema = z.object({
  q: z.string().nullable(),
  search_fields: z.array(z.string()).nullable(),
  filters: z.record(z.string(), z.any()),
  sort_by: z.string().nullable(),
  sort_direction: z.string().nullable(),
  limit: z.number().nullable(),
  offset: z.number().nullable(),
  user_id: z.string().nullable(),
  favorites_only: z.boolean().nullable(),
  min_rating: z.number().nullable()
});
export type QueryParams = z.infer<typeof QueryParamsSchema>;

export const RedeemInviteRequestSchema = z.object({
  invite_code: z.string(),
  username: z.string()
});
export type RedeemInviteRequest = z.infer<typeof RedeemInviteRequestSchema>;

export const RegisterStartRequestSchema = z.object({
  username: z.string(),
  invite_code: z.string().nullable()
});
export type RegisterStartRequest = z.infer<typeof RegisterStartRequestSchema>;

export const StartLoginRequestSchema = z.object({
  username: z.string()
});
export type StartLoginRequest = z.infer<typeof StartLoginRequestSchema>;

export const WhoAmIResponseSchema = z.object({
  user_id: z.string(),
  username: z.string(),
  role: z.string()
});
export type WhoAmIResponse = z.infer<typeof WhoAmIResponseSchema>;

