#!/usr/bin/env bash
# stages a self-contained, bundleable libmpv for macOS into
# client/charnel/src-tauri/mpv-runtime/lib (referenced by
# tauri.macos.conf.json's `bundle.macOS.frameworks`, regenerated by this
# script every run since the exact dependency filenames drift with
# homebrew's own package versions) - so end users never need homebrew (or
# anything else) installed to run charnel.
#
# arm64: bundles homebrew's REAL mpv build (`brew install mpv`) - this is
# the actual, working, fully-featured mpv anyone gets locally too. its
# dependency closure (ffmpeg, libass, libplacebo, ~45 dylibs) has absolute
# /opt/homebrew/... install names, not portable as-is - `dylibbundler`
# copies the whole closure into one flat directory and rewrites every
# install name to be @loader_path-relative, making it fully self-contained.
# confirmed for real (2026-09-30): the prebuilt `mpv-libre-runtime` project
# (tried first, see git history) turned out to have a broken Vulkan-only
# GPU renderer on macOS (`vid=no`, silently audio-only, no window) -
# homebrew's own build doesn't have this problem, it just needed proper
# bundling.
#
# x86_64: homebrew has no x86_64 macOS bottle for mpv at all anymore (and
# modern homebrew's installer refuses fresh x86_64 installs outright, even
# under rosetta) - still uses the mpv-libre-runtime prebuilt archive here.
# this needs revisiting too (tracked as a separate follow-up) but is out
# of scope for this pass.
#
# usage: scripts/fetch-mpv-runtime.sh <arm64|x86_64>
set -euo pipefail

ARCH="${1:?usage: fetch-mpv-runtime.sh <arm64|x86_64>}"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUNDLE_DEST="$REPO_ROOT/client/charnel/src-tauri/mpv-runtime/lib"
CONF_PATH="$REPO_ROOT/client/charnel/src-tauri/tauri.macos.conf.json"

case "$ARCH" in
  arm64)
    if ! [ -f /opt/homebrew/opt/mpv/lib/libmpv.2.dylib ]; then
      echo "fetch-mpv-runtime: installing mpv via homebrew..."
      brew install mpv
    fi
    if ! command -v dylibbundler >/dev/null 2>&1; then
      echo "fetch-mpv-runtime: installing dylibbundler via homebrew..."
      brew install dylibbundler
    fi

    rm -rf "$BUNDLE_DEST"
    mkdir -p "$BUNDLE_DEST"
    cp /opt/homebrew/opt/mpv/lib/libmpv.2.dylib "$BUNDLE_DEST/"

    # flat directory + uniform @loader_path/ for every rewrite (not
    # @loader_path/Frameworks/ or similar): dylibbundler rewrites every
    # dependency's references using the SAME -p prefix regardless of
    # whether that dependency itself lives at the top level or is a
    # dependency-of-a-dependency already inside -d's directory - a nested
    # prefix doubles up (Frameworks/Frameworks/...) for anything but the
    # top-level -x target. keeping everything in one flat dir with a bare
    # @loader_path/ sidesteps that entirely.
    (cd "$BUNDLE_DEST" && dylibbundler -b -of -cd -x libmpv.2.dylib -d . -p "@loader_path/" </dev/null)

    # dylibbundler adds an @loader_path/ rpath to the -x target that's
    # entirely redundant (every rewritten reference already uses an
    # explicit @loader_path/<name> path, not @rpath/<name>) and, for
    # reasons not fully understood, sometimes adds it twice - a literal
    # duplicate LC_RPATH load command, which ld refuses to link against
    # ("duplicate LC_RPATH") once anything depends on this dylib. strip it.
    for f in "$BUNDLE_DEST"/*.dylib; do
      count=$(otool -l "$f" | grep -c "path @loader_path/ (offset" || true)
      if [ "$count" -gt 1 ]; then
        install_name_tool -delete_rpath "@loader_path/" "$f"
      fi
    done

    # the -x target's own install name (id) is untouched by dylibbundler -
    # still homebrew's absolute path. rewrite it so it's resolvable once
    # bundled - client/charnel/scripts/fixup-mpv-install-name.sh separately
    # rewrites OUR OWN executable's reference to this same file (baked in
    # at link time from this exact string) to
    # @executable_path/../Frameworks/libmpv.2.dylib.
    install_name_tool -id "@loader_path/libmpv.2.dylib" "$BUNDLE_DEST/libmpv.2.dylib"

    # every install_name_tool edit above invalidates whatever signature was
    # there before (homebrew's own, or none) - ad-hoc re-sign so dyld's
    # runtime validation doesn't refuse to load these (confirmed for real:
    # an unsigned/invalidated dylib gets the whole process SIGKILLed with
    # zero diagnostic output at all, easy to mistake for a rendering bug).
    codesign --force --sign - "$BUNDLE_DEST"/*.dylib

    # regenerate tauri.macos.conf.json's frameworks list from whatever's
    # actually present - homebrew's ffmpeg/libass/etc versions drift over
    # time (different exact filenames each upgrade), so this can't be a
    # fixed/hardcoded list checked into git (see this file's own
    # .gitignore entry).
    python3 - "$BUNDLE_DEST" "$CONF_PATH" <<'PYEOF'
import json
import os
import sys

bundle_dest, conf_path = sys.argv[1], sys.argv[2]
files = sorted(f for f in os.listdir(bundle_dest) if f.endswith(".dylib"))
conf = {
    "build": {"beforeBundleCommand": "scripts/fixup-mpv-install-name.sh"},
    "bundle": {"macOS": {"frameworks": [f"mpv-runtime/lib/{f}" for f in files]}},
}
with open(conf_path, "w") as fh:
    json.dump(conf, fh, indent=2)
    fh.write("\n")
PYEOF

    count=$(find "$BUNDLE_DEST" -name '*.dylib' | wc -l | tr -d ' ')
    echo "fetch-mpv-runtime: bundled $count dylibs from homebrew's mpv, regenerated $CONF_PATH"
    ;;

  x86_64)
    RELEASE_TAG="runtime-mpv-2a4eb8067c-librempeg-9c00336e26-fb08030026"
    ASSET="mpv-libre-runtime-darwin-x64.tar.xz"
    EXPECTED_SHA256="99995d48421e0fcd2c24152cf4bb4523b86e30294d105e9a3683e6da92b3cdc5"
    BASE_URL="https://github.com/Zencok/mpv-libre-runtime/releases/download/$RELEASE_TAG"
    LINK_DEST="/usr/local/lib"
    STAMP="$BUNDLE_DEST/.fetched-x86_64-$RELEASE_TAG"

    if [ -f "$STAMP" ] && [ -f "$LINK_DEST/libmpv.dylib" ]; then
      echo "fetch-mpv-runtime: already staged for x86_64 at this release, skipping download"
      exit 0
    fi

    TMP="$(mktemp -d)"
    trap 'rm -rf "$TMP"' EXIT

    echo "fetch-mpv-runtime: downloading $ASSET..."
    curl -fsSL -o "$TMP/$ASSET" "$BASE_URL/$ASSET"
    echo "$EXPECTED_SHA256  $TMP/$ASSET" | shasum -a 256 -c -
    tar -xf "$TMP/$ASSET" -C "$TMP"

    mkdir -p "$BUNDLE_DEST"
    cp "$TMP/lib/libmpv.2.dylib" "$TMP/lib/libgraphite2.3.dylib" "$TMP/lib/libvulkan.1.dylib" "$BUNDLE_DEST/"
    echo "fetch-mpv-runtime: staged for bundling at $BUNDLE_DEST"

    # /usr/local is root:wheel 755 on a stock macOS install (no homebrew
    # ever installed there) - happens on apple silicon since homebrew's
    # native prefix is /opt/homebrew instead. bootstrap it once with
    # non-interactive sudo (works passwordlessly on github's macos
    # runners) - never prompts for a password locally. not fatal if it
    # fails: only actually required for this x86_64 path (no real mpv
    # install exists otherwise to satisfy the linker's -lmpv).
    if [ ! -w "$LINK_DEST" ] && [ ! -d "$LINK_DEST" ]; then
      if ! (sudo -n mkdir -p "$LINK_DEST" && sudo -n chown "$(id -u):$(id -g)" "$LINK_DEST") 2>/dev/null; then
        echo "fetch-mpv-runtime: warning: $LINK_DEST isn't writable and isn't sudo-creatable non-interactively - skipping the linker copy." >&2
        echo "fetch-mpv-runtime: if \`cargo build\` fails to find -lmpv, run once: sudo mkdir -p $LINK_DEST && sudo chown \$(id -u):\$(id -g) $LINK_DEST" >&2
        touch "$STAMP"
        exit 0
      fi
    fi

    mkdir -p "$LINK_DEST"
    cp "$TMP/lib/libmpv.2.dylib" "$TMP/lib/libgraphite2.3.dylib" "$TMP/lib/libvulkan.1.dylib" "$LINK_DEST/"
    ln -sf libmpv.2.dylib "$LINK_DEST/libmpv.dylib"
    echo "fetch-mpv-runtime: staged for linking at $LINK_DEST"

    touch "$STAMP"
    ;;

  *)
    echo "fetch-mpv-runtime.sh: unknown arch '$ARCH' (expected arm64 or x86_64)" >&2
    exit 1
    ;;
esac
