#!/usr/bin/env bash
# stages libmpv for macOS, bundled + hard-linked + fully self-contained on
# BOTH architectures - end users never need homebrew (or anything else)
# installed to run charnel.
#
# arm64: bundles homebrew's REAL mpv build (`brew install mpv` against the
# system /opt/homebrew prefix) into
# client/charnel/src-tauri/mpv-runtime/lib (referenced by
# tauri.macos.conf.json's `bundle.macOS.frameworks`, regenerated by this
# script every run since the exact dependency filenames drift with
# homebrew's own package versions).
#
# x86_64: homebrew dropped bottle (prebuilt binary) support for Intel
# macOS entirely as of ~September 2026 (`brew install mpv` now prints an
# explicit "we do not provide support for this platform" warning) - but
# building from source still works fine (requires a full Xcode.app
# install, not just the Command Line Tools - `deno`, a transitive
# dependency via yt-dlp, and `molten-vk` both refuse to build without
# it). it's ~86 formulas deep (ffmpeg, libplacebo, llvm, rust, ... - a
# multi-hour build the first time). bootstraps its own relocatable
# homebrew prefix at /Users/Shared/freqhole-homebrew-x86 (homebrew
# refuses to run from /tmp, see git history) rather than touching the
# system /usr/local, and runs every brew command under `arch -x86_64`
# (rosetta) since this machine's real arch is whatever `uname -m` says,
# not necessarily x86_64.
#
# both architectures' bundled dylib closures get committed to git under
# mpv-runtime/committed/<arch> once built (see stage_from_committed
# below) - CI and fresh local checkouts reuse that committed snapshot by
# default instead of redoing the slow homebrew build every single run.
#
# both architectures' mpv dependency closure (ffmpeg, libass, libplacebo,
# ~45-90 dylibs) has absolute install names pointing at wherever homebrew
# put them, not portable as-is - `dylibbundler` copies the whole closure
# into one flat directory and rewrites every install name to be
# @loader_path-relative, making it fully self-contained. see
# `bundle_mpv_dylib_closure` below (shared by both arch branches).
#
# history: this used to be a from-scratch weak-linking setup for x86_64
# (optional libmpv, never bundled) after both the prebuilt
# `mpv-libre-runtime` project AND homebrew's arm64 mpv build appeared to
# have a broken Vulkan-only GPU renderer on macOS (`vid=no`/`current-vo`
# unavailable, `VK_ERROR_INCOMPATIBLE_DRIVER` even with a real MoltenVK
# ICD explicitly supplied). confirmed for real later (2026-09-30) that
# this was never actually a broken renderer at all - it was macOS
# hardened runtime's Library Validation blocking `dlopen` of the
# ad-hoc-signed MoltenVK dylib the vulkan loader needs at runtime (fixed
# via `com.apple.security.cs.disable-library-validation` in
# client/charnel/src-tauri/macos/entitlements.plist). once that was
# understood, bundling homebrew's real mpv (arm64) and building mpv from
# source (x86_64) both just worked.
#
# usage: scripts/fetch-mpv-runtime.sh <arm64|x86_64> [--rebuild]
#
# by default, if client/charnel/src-tauri/mpv-runtime/committed/<arch>
# already has a bundled dylib closure checked into git, this just copies
# it into place (seconds, no homebrew/network/compiler needed at all) -
# pass --rebuild to force redoing the real homebrew fetch+build+bundle
# below and refresh that committed snapshot (e.g. to pick up a newer mpv
# release).
set -euo pipefail

ARCH="${1:?usage: fetch-mpv-runtime.sh <arm64|x86_64> [--rebuild]}"
REBUILD="${2:-}"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUNDLE_DEST="$REPO_ROOT/client/charnel/src-tauri/mpv-runtime/lib"
COMMITTED_DIR="$REPO_ROOT/client/charnel/src-tauri/mpv-runtime/committed/$ARCH"
CONF_PATH="$REPO_ROOT/client/charnel/src-tauri/tauri.macos.conf.json"

# regenerates tauri.macos.conf.json to reference every dylib currently in
# $BUNDLE_DEST - shared by both the committed-snapshot fast path and the
# real bundle_mpv_dylib_closure slow path below.
#
# $1: "true" to also set bundle.macOS.minimumSystemVersion to 14.0 (x86_64
#     only - arm64's rustc default of 11.0 is already fine).
regen_tauri_conf() {
    local need_min_version="$1"
    python3 - "$BUNDLE_DEST" "$CONF_PATH" "$need_min_version" <<'PYEOF'
import json
import os
import sys

bundle_dest, conf_path, need_min_version = sys.argv[1], sys.argv[2], sys.argv[3]
entries = sorted(os.listdir(bundle_dest))
dylibs = [f for f in entries if f.endswith(".dylib")]
# tauri's `bundle.macOS.frameworks` requires actual dylibs/.frameworks -
# the MoltenVK ICD manifest (plain json) and the bundled ffmpeg/ffprobe
# CLI binaries (plain executables, no extension) are all read/exec'd at
# runtime rather than something macOS treats as a loadable framework, so
# they belong under `bundle.resources` instead (rejected with "Framework
# path should have .framework extension" otherwise).
resources = [f for f in entries if f.endswith(".json") or f in ("ffmpeg", "ffprobe")]
conf = {
    "build": {"beforeBundleCommand": "scripts/fixup-mpv-install-name.sh"},
    "bundle": {
        "macOS": {"frameworks": [f"mpv-runtime/lib/{f}" for f in dylibs]},
        "resources": [f"mpv-runtime/lib/{f}" for f in resources],
    },
}
if need_min_version == "true":
    conf["bundle"]["macOS"]["minimumSystemVersion"] = "14.0"
with open(conf_path, "w") as fh:
    json.dump(conf, fh, indent=2)
    fh.write("\n")
PYEOF
}

# copies the committed/<arch> snapshot into $BUNDLE_DEST - the fast path,
# used whenever that snapshot exists and --rebuild wasn't passed.
#
# $1: "true" to set bundle.macOS.minimumSystemVersion (see regen_tauri_conf).
# $2: optional - if set, also stage libmpv.2.dylib (+ unversioned symlink)
#     at this path, so `cargo build`'s `-lmpv` linker step (e.g. rathole,
#     which links libmpv directly rather than bundling it tauri-style)
#     has a real file to resolve against without needing a real `brew
#     install mpv` ever run on this machine - both arches use this (see
#     each branch below for the path): arm64's committed fast path never
#     installs homebrew's real mpv at all, so it needs this just as much
#     as x86_64 does.
stage_from_committed() {
    local need_min_version="$1"
    local linker_stub_dir="${2:-}"

    rm -rf "$BUNDLE_DEST"
    mkdir -p "$BUNDLE_DEST"
    cp "$COMMITTED_DIR"/*.dylib "$BUNDLE_DEST/"
    # MoltenVK's ICD manifest (see bundle_mpv_dylib_closure) - not every
    # committed/<arch> snapshot necessarily has one yet, so don't fail if
    # the glob matches nothing.
    cp "$COMMITTED_DIR"/*.json "$BUNDLE_DEST/" 2>/dev/null || true
    # bundled ffmpeg/ffprobe CLI binaries (see bundle_mpv_dylib_closure) -
    # same "not every snapshot has one yet" caveat as the json manifest.
    cp "$COMMITTED_DIR/ffmpeg" "$COMMITTED_DIR/ffprobe" "$BUNDLE_DEST/" 2>/dev/null || true
    # homebrew-built dylibs are mode 444 - tauri-bundler's xattr/codesign
    # steps need write access to touch them at all.
    chmod u+w "$BUNDLE_DEST"/*.dylib
    chmod u+w "$BUNDLE_DEST/ffmpeg" "$BUNDLE_DEST/ffprobe" 2>/dev/null || true
    regen_tauri_conf "$need_min_version"

    if [ -n "$linker_stub_dir" ]; then
        mkdir -p "$linker_stub_dir"
        # homebrew-built dylibs are mode 444 (read-only) - `cp` propagates
        # that, and a stale copy from a previous run would then make a
        # plain `cp`/`ln -sf` here fail outright. `rm -f` only needs the
        # *directory* to be writable (not the target file itself), so
        # always clear these two files first rather than relying on them
        # not existing yet.
        rm -f "$linker_stub_dir/libmpv.2.dylib" "$linker_stub_dir/libmpv.dylib"
        cp -f "$COMMITTED_DIR/libmpv.2.dylib" "$linker_stub_dir/"
        chmod u+w "$linker_stub_dir/libmpv.2.dylib"
        ln -sf libmpv.2.dylib "$linker_stub_dir/libmpv.dylib"
    fi

    count=$(find "$BUNDLE_DEST" -name '*.dylib' | wc -l | tr -d ' ')
    echo "fetch-mpv-runtime: staged $count dylibs from committed/$ARCH (pass --rebuild to refresh from a fresh homebrew build)"
}

# bundles a built mpv dylib (and its full dependency closure) into
# $BUNDLE_DEST, regenerates tauri.macos.conf.json, and refreshes
# committed/<arch> so future runs can skip straight to the fast path
# above - shared by both arch branches below, which differ only in HOW
# they get homebrew's mpv built/installed in the first place.
#
# $1: path to the homebrew-built libmpv.2.dylib to bundle.
# $2: "true" to also set bundle.macOS.minimumSystemVersion to 14.0 in the
#     generated config (x86_64 only - arm64's rustc default of 11.0 is
#     already fine).
# $3: brew invocation to use for `--prefix molten-vk` lookups (e.g. "brew"
#     or `arch -x86_64 /path/to/brew`) - word-split unquoted below, so
#     must not itself contain anything needing quoting/escaping.
bundle_mpv_dylib_closure() {
    local src_mpv_dylib="$1"
    local need_min_version="$2"
    local brew_cmd="$3"

    if ! command -v dylibbundler >/dev/null 2>&1; then
        echo "fetch-mpv-runtime: installing dylibbundler via homebrew..."
        brew install dylibbundler
    fi

    rm -rf "$BUNDLE_DEST"
    mkdir -p "$BUNDLE_DEST"
    cp "$src_mpv_dylib" "$BUNDLE_DEST/"
    chmod u+w "$BUNDLE_DEST"/*.dylib

    # flat directory + uniform @loader_path/ for every rewrite (not
    # @loader_path/Frameworks/ or similar): dylibbundler rewrites every
    # dependency's references using the SAME -p prefix regardless of
    # whether that dependency itself lives at the top level or is a
    # dependency-of-a-dependency already inside -d's directory - a nested
    # prefix doubles up (Frameworks/Frameworks/...) for anything but the
    # top-level -x target. keeping everything in one flat dir with a bare
    # @loader_path/ sidesteps that entirely.
    (cd "$BUNDLE_DEST" && dylibbundler -b -of -cd -x libmpv.2.dylib -d . -p "@loader_path/" </dev/null)

    # dylibbundler adds an @loader_path/ rpath to the -x target that's
    # entirely redundant (every rewritten reference already uses an
    # explicit @loader_path/<name> path, not @rpath/<name>) and, for
    # reasons not fully understood, sometimes adds it twice - a literal
    # duplicate LC_RPATH load command, which ld refuses to link against
    # ("duplicate LC_RPATH") once anything depends on this dylib. strip it.
    for f in "$BUNDLE_DEST"/*.dylib; do
        count=$(otool -l "$f" | grep -c "path @loader_path/ (offset" || true)
        if [ "$count" -gt 1 ]; then
            install_name_tool -delete_rpath "@loader_path/" "$f"
        fi
    done

    # the -x target's own install name (id) is untouched by dylibbundler -
    # still homebrew's absolute path. rewrite it so it's resolvable once
    # bundled - client/charnel/scripts/fixup-mpv-install-name.sh separately
    # rewrites OUR OWN executable's reference to this same file (baked in
    # at link time from this exact string) to
    # @executable_path/../Frameworks/libmpv.2.dylib.
    install_name_tool -id "@loader_path/libmpv.2.dylib" "$BUNDLE_DEST/libmpv.2.dylib"

    # every install_name_tool edit above invalidates whatever signature was
    # there before (homebrew's own, or none) - ad-hoc re-sign so dyld's
    # runtime validation doesn't refuse to load these (confirmed for real:
    # an unsigned/invalidated dylib gets the whole process SIGKILLed with
    # zero diagnostic output at all, easy to mistake for a rendering bug).
    codesign --force --sign - "$BUNDLE_DEST"/*.dylib

    # MoltenVK (the actual vulkan ICD/driver) isn't a static dependency of
    # libmpv.2.dylib - mpv's vulkan vo finds it at runtime via the vulkan
    # LOADER's own ICD-manifest discovery (a json file pointing at the
    # dylib), not a normal dlopen of a linked dependency - so dylibbundler
    # never sees or bundles it, even though libvulkan.1.dylib (the loader
    # itself) gets swept up fine. without this, the bundled app has a
    # vulkan loader with no driver to find at all: every vo/gpu context
    # fails identically with VK_ERROR_INCOMPATIBLE_DRIVER (confirmed for
    # real 2026-10-02 via mpv's own verbose log - audio plays, no video
    # window, no error dialog). bundle the dylib as a `frameworks` entry
    # (ends up flat at Contents/Frameworks/) and the manifest as a
    # `resources` entry (tauri rejects non-.dylib/.framework paths under
    # `frameworks` - "Framework path should have .framework extension" -
    # but resources entries preserve their FULL given relative path
    # instead of flattening, landing at
    # Contents/Resources/mpv-runtime/lib/MoltenVK_icd.json, confirmed via
    # an actual local build 2026-10-02) - so `library_path` can't be a
    # bare filename (the vulkan loader resolves non-absolute paths
    # relative to the manifest's OWN directory, which is no longer the
    # same directory as the dylib once they're split across
    # Frameworks/Resources like this). client/charnel's own startup code
    # points $VK_ICD_FILENAMES at this bundled manifest before mpv ever
    # touches vulkan - see video_window/libmpv_backend.rs.
    local moltenvk_prefix
    moltenvk_prefix=$($brew_cmd --prefix molten-vk 2>/dev/null || true)
    if [ -n "$moltenvk_prefix" ] && [ -f "$moltenvk_prefix/lib/libMoltenVK.dylib" ]; then
        cp "$moltenvk_prefix/lib/libMoltenVK.dylib" "$BUNDLE_DEST/"
        chmod u+w "$BUNDLE_DEST/libMoltenVK.dylib"
        install_name_tool -id "@loader_path/libMoltenVK.dylib" "$BUNDLE_DEST/libMoltenVK.dylib"
        codesign --force --sign - "$BUNDLE_DEST/libMoltenVK.dylib"

        python3 - "$moltenvk_prefix/etc/vulkan/icd.d/MoltenVK_icd.json" "$BUNDLE_DEST/MoltenVK_icd.json" <<'PYEOF'
import json
import sys

src, dest = sys.argv[1], sys.argv[2]
with open(src) as f:
    manifest = json.load(f)
# Contents/Resources/mpv-runtime/lib/MoltenVK_icd.json (this file) ->
# Contents/Frameworks/libMoltenVK.dylib (3 levels up, then into Frameworks).
manifest["ICD"]["library_path"] = "../../../Frameworks/libMoltenVK.dylib"
with open(dest, "w") as f:
    json.dump(manifest, f, indent=4)
    f.write("\n")
PYEOF
    else
        echo "fetch-mpv-runtime: warning - molten-vk not found via '$brew_cmd --prefix molten-vk', bundled app's vulkan video output will not work" >&2
    fi

    # bundles ffmpeg/ffprobe (plain CLI binaries, used by grimoire's own
    # transcode/thumbnail/probe code via Command::new - a completely
    # separate code path from libmpv above) reusing THIS SAME dylib
    # closure, rather than a second independent copy of every ffmpeg lib -
    # confirmed for real 2026-10-02 that homebrew's standalone `ffmpeg`
    # formula (a direct dependency of `mpv`, always installed alongside
    # it) is ABI-compatible with mpv's own linked copies: matching
    # SONAMEs/compatibility versions, and a real `dylibbundler` pass
    # against the already-populated $BUNDLE_DEST correctly recognized
    # every dependency as already present (49 dylibs before, 49 after -
    # zero duplicates) and rewrote ffmpeg/ffprobe's references to them
    # directly, verified with a real libx264 encode + ffprobe decode in
    # the exact final bundle layout.
    #
    # ffmpeg/ffprobe are plain executables (no extension) - like
    # MoltenVK_icd.json above, tauri's `frameworks` key rejects them
    # ("Framework path should have .framework extension"), so they're
    # bundled as `resources` entries too, landing at
    # Contents/Resources/mpv-runtime/lib/{ffmpeg,ffprobe} (3 levels
    # removed from Contents/Frameworks/ where the dylibs actually live -
    # same nesting the MoltenVK manifest's library_path already accounts
    # for). client/charnel's own ffmpeg-path resolution prefers this
    # bundled copy, falling back to the user's own configured/PATH
    # ffmpeg if bundling failed or on non-macOS - see
    # grimoire/src/config.rs.
    local ffmpeg_prefix
    ffmpeg_prefix=$($brew_cmd --prefix ffmpeg 2>/dev/null || true)
    if [ -n "$ffmpeg_prefix" ] && [ -f "$ffmpeg_prefix/bin/ffmpeg" ] && [ -f "$ffmpeg_prefix/bin/ffprobe" ]; then
        cp "$ffmpeg_prefix/bin/ffmpeg" "$ffmpeg_prefix/bin/ffprobe" "$BUNDLE_DEST/"
        chmod u+w "$BUNDLE_DEST/ffmpeg" "$BUNDLE_DEST/ffprobe"
        (cd "$BUNDLE_DEST" && dylibbundler -b -of -cd -x ffmpeg -x ffprobe -d . -p "@executable_path/../../../Frameworks/" </dev/null)
        for f in "$BUNDLE_DEST/ffmpeg" "$BUNDLE_DEST/ffprobe"; do
            count=$(otool -l "$f" | grep -c "path @executable_path/../../../Frameworks/ (offset" || true)
            if [ "$count" -gt 1 ]; then
                install_name_tool -delete_rpath "@executable_path/../../../Frameworks/" "$f"
            fi
        done
    else
        echo "fetch-mpv-runtime: warning - ffmpeg not found via '$brew_cmd --prefix ffmpeg', bundled app will fall back to the user's own ffmpeg/ffprobe install" >&2
    fi

    regen_tauri_conf "$need_min_version"

    # refresh the committed snapshot so future runs (CI included) can use
    # the fast path above instead of rebuilding mpv from source again.
    rm -rf "$COMMITTED_DIR"
    mkdir -p "$COMMITTED_DIR"
    cp "$BUNDLE_DEST"/*.dylib "$COMMITTED_DIR/"
    cp "$BUNDLE_DEST"/*.json "$COMMITTED_DIR/" 2>/dev/null || true
    cp "$BUNDLE_DEST/ffmpeg" "$BUNDLE_DEST/ffprobe" "$COMMITTED_DIR/" 2>/dev/null || true

    count=$(find "$BUNDLE_DEST" -name '*.dylib' | wc -l | tr -d ' ')
    echo "fetch-mpv-runtime: bundled $count dylibs from homebrew's mpv, regenerated $CONF_PATH, refreshed committed/$ARCH"
}

case "$ARCH" in
  arm64)
    if [ -d "$COMMITTED_DIR" ] && [ "$REBUILD" != "--rebuild" ]; then
      # /Users/Shared (world-writable, no sudo needed, not per-user like
      # $HOME - same reasoning as x86_64's stub dir below) matches a
      # second `.cargo/config.toml` rustflags `-L` entry for this target -
      # a clean CI runner never runs `brew install mpv` on this fast
      # path, so without this, rathole's `-lmpv` has nothing to resolve
      # against (confirmed for real 2026-10-02: `make build-mac-arm`
      # failed in CI with "library 'mpv' not found" despite charnel's own
      # bundling succeeding, since charnel only needs the dylib *copied*
      # into its app bundle, never linked against at compile time).
      # /usr/local/lib (this target's other `-L` entry) would also work on
      # CI's runner but needs sudo on a normal dev mac, so this dedicated
      # path is used instead - safe to pass unconditionally either way.
      stage_from_committed false "/Users/Shared/freqhole-mpv-arm64/lib"
      exit 0
    fi

    if ! [ -f /opt/homebrew/opt/mpv/lib/libmpv.2.dylib ]; then
      echo "fetch-mpv-runtime: installing mpv via homebrew..."
      brew install mpv
    fi
    bundle_mpv_dylib_closure /opt/homebrew/opt/mpv/lib/libmpv.2.dylib false brew
    ;;

  x86_64)
    if [ -d "$COMMITTED_DIR" ] && [ "$REBUILD" != "--rebuild" ]; then
      # same fixed path .cargo/config.toml's x86_64 rustflags point `-L`
      # at - stage_from_committed drops libmpv.2.dylib there too so
      # `cargo build --target x86_64-apple-darwin`'s `-lmpv` resolves
      # without needing homebrew (or any build) at all.
      stage_from_committed true "/Users/Shared/freqhole-homebrew-x86/opt/mpv/lib"
      exit 0
    fi

    # homebrew refuses to run from a prefix inside its own temp directory
    # (anything under /tmp) - this is a real, persistent, relocatable
    # install (not a throwaway), so /Users/Shared (world-writable on every
    # mac, no sudo needed, NOT per-user like $HOME) is the right home for
    # it: a fixed, known-at-config-write-time path is required since
    # .cargo/config.toml's rustflags are static strings with no shell/env
    # expansion, and this same path needs to agree with the one baked in
    # there. cacheable across CI runs (actions/cache keyed on this path
    # avoids re-running the ~86-formula from-source build every single
    # release) and persists across local dev sessions the same way the
    # arm64 branch's system /opt/homebrew already does.
    BREW_PREFIX="/Users/Shared/freqhole-homebrew-x86"
    if ! [ -x "$BREW_PREFIX/bin/brew" ]; then
      echo "fetch-mpv-runtime: bootstrapping a relocatable x86_64 homebrew at $BREW_PREFIX..."
      mkdir -p "$BREW_PREFIX"
      curl -fsSL https://github.com/Homebrew/brew/tarball/main \
        | tar xz --strip-components 1 -C "$BREW_PREFIX"
    fi

    if ! [ -f "$BREW_PREFIX/opt/mpv/lib/libmpv.2.dylib" ]; then
      echo "fetch-mpv-runtime: installing mpv (targeting macOS 14.0) via x86_64 homebrew (from source - homebrew no longer ships Intel macOS bottles; this can take a long time the first run, cached after)..."
      # homebrew otherwise builds against whatever macOS version is
      # running ON THIS MACHINE (not a fixed minimum) - mpv's cocoa
      # backend is partly written in Swift, so an unpinned build here
      # silently links against Swift runtime symbols only present on THIS
      # machine's OS, crashing at launch on an older-but-still->=14 target
      # Mac with "Symbol not found" against libswiftCore.dylib (confirmed
      # for real 2026-10-02).
      #
      # a plain `export MACOSX_DEPLOYMENT_TARGET=14.0` before `brew
      # install` does NOT work, nor does `HOMEBREW_FAKE_MACOS=14.0`
      # (homebrew's own internal "pretend to be running an older macOS"
      # escape hatch) - confirmed empirically both leave `otool -l`
      # showing `minos 15.0` (the host's real OS version) afterward:
      # homebrew's superenv sandbox strips/ignores arbitrary inherited env
      # vars (and mpv's meson-based formula never itself forwards
      # MACOSX_DEPLOYMENT_TARGET to the swiftc/clang subprocesses it
      # spawns), and mpv's own swiftc invocation never passes an explicit
      # `-target`/version-min flag either - so the ONLY thing that
      # actually works is setting ENV["MACOSX_DEPLOYMENT_TARGET"] from
      # *inside* the formula's own `install` method, which runs AFTER
      # superenv's sanitization and so genuinely persists into every
      # meson/ninja/swiftc subprocess it spawns. confirmed via `otool -l`
      # showing `minos 14.0` afterward.
      #
      # homebrew refuses to load/install a bare formula.rb path directly
      # ("Homebrew requires formulae to be in a tap") - so this
      # regenerates a tiny persistent local tap each run from whatever
      # mpv.rb homebrew-core currently ships (keeping it in sync with
      # upstream mpv version/patch bumps automatically) with that one
      # line patched in, and installs from the patched copy instead of
      # plain `brew install mpv`.
      #
      # minos 14.0 alone isn't enough: mpv's cocoa backend is partly
      # Swift, and whatever Xcode built it determines which Swift stdlib
      # ABI symbols get emitted, independent of the deployment-target
      # flag (confirmed for real 2026-10-02 - a minos-14.0 build still
      # referenced `_$ss20__StaticArrayStorageCN`, a symbol added to the
      # Swift runtime around the macOS 15 SDK, absent from macOS 14's
      # system libswiftCore.dylib). pinning DEVELOPER_DIR at a
      # side-by-side Xcode 15.4 (last release on the macOS 14 SDK,
      # Swift 5.9/5.10) avoids that codegen path entirely - only applied
      # if that specific Xcode happens to be installed, so this degrades
      # to "whatever Xcode is active" everywhere else (CI included, until
      # pinned there too).
      #
      # DEVELOPER_DIR alone did NOT work either (confirmed for real
      # 2026-10-02, round two - a rebuild with DEVELOPER_DIR pinned to
      # Xcode 15.4 still showed `sdk 15.4` in `otool -l`'s
      # LC_BUILD_VERSION, and `dyld_info -imports` still listed
      # `_$ss20__StaticArrayStorageCN` - nm's classic symbol-table view
      # doesn't surface this symbol at all since it's bound via newer
      # chained fixups, so always use dyld_info to check for it, not nm):
      # homebrew's superenv sandbox precomputes an absolute SDKROOT
      # pointing at whatever Xcode is active BEFORE `install` ever runs,
      # and meson/swiftc read that env var directly rather than invoking
      # `xcrun` themselves - so DEVELOPER_DIR changes which `xcrun`
      # resolves to if something calls it, but does nothing for a tool
      # that just reads the already-exported SDKROOT. explicitly
      # overriding SDKROOT too (via the system `/usr/bin/xcrun` - xcrun
      # itself isn't bundled per-Xcode-copy, it resolves SDKs through
      # whatever DEVELOPER_DIR points at) closes that gap.
      PINNED_XCODE="/Applications/Xcode_15.4.app"
      LOCAL_TAP_DIR="$BREW_PREFIX/Library/Taps/freqhole-local/homebrew-mpv-patched"
      if ! [ -d "$LOCAL_TAP_DIR" ]; then
        arch -x86_64 "$BREW_PREFIX/bin/brew" tap-new freqhole-local/mpv-patched
      fi
      arch -x86_64 "$BREW_PREFIX/bin/brew" cat mpv > "$LOCAL_TAP_DIR/Formula/mpv.rb"
      python3 - "$LOCAL_TAP_DIR/Formula/mpv.rb" "$PINNED_XCODE" <<'PYEOF'
import sys

path, pinned_xcode = sys.argv[1], sys.argv[2]
with open(path) as f:
    content = f.read()
marker = "  def install\n"
idx = content.index(marker) + len(marker)
pinned_developer_dir = f"{pinned_xcode}/Contents/Developer"
injects = [
    '    ENV["MACOSX_DEPLOYMENT_TARGET"] = "14.0" if OS.mac?\n',
    f'    if OS.mac? && File.directory?("{pinned_xcode}")\n'
    f'      ENV["DEVELOPER_DIR"] = "{pinned_developer_dir}"\n'
    # xcrun isn't bundled per-Xcode-copy - it's the single system
    # /usr/bin/xcrun, which resolves SDKs via the DEVELOPER_DIR just set
    # above (already inherited since it's a plain ENV assignment).
    f'      ENV["SDKROOT"] = Utils.safe_popen_read("/usr/bin/xcrun", "--sdk", "macosx", "--show-sdk-path").strip\n'
    f'    end\n',
]
for inject in injects:
    if inject not in content:
        content = content[:idx] + inject + content[idx:]
        idx += len(inject)
with open(path, "w") as f:
    f.write(content)
PYEOF
      arch -x86_64 "$BREW_PREFIX/bin/brew" install --build-from-source freqhole-local/mpv-patched/mpv
    fi
    if ! arch -x86_64 "$BREW_PREFIX/bin/brew" list dylibbundler >/dev/null 2>&1; then
      echo "fetch-mpv-runtime: installing dylibbundler via x86_64 homebrew..."
      arch -x86_64 "$BREW_PREFIX/bin/brew" install dylibbundler
    fi
    # file-manipulation tools (install_name_tool/codesign/otool/
    # dylibbundler) just read+rewrite mach-o load commands - they don't
    # need to run AS x86_64 to edit an x86_64 dylib, and macOS
    # transparently invokes rosetta for any x86_64 binary regardless of
    # how it's launched, so no `arch -x86_64` wrapping is needed here.
    # PATH-prepend so `dylibbundler` resolves to the x86_64 homebrew's
    # own copy (matching the architecture of the files it's rewriting).
    export PATH="$BREW_PREFIX/bin:$PATH"
    bundle_mpv_dylib_closure "$BREW_PREFIX/opt/mpv/lib/libmpv.2.dylib" true "arch -x86_64 $BREW_PREFIX/bin/brew"
    ;;

  *)
    echo "fetch-mpv-runtime.sh: unknown arch '$ARCH' (expected arm64 or x86_64)" >&2
    exit 1
    ;;
esac

