-- update test albums script
-- adds ~200 distinct artist/album combinations with _TEST suffix
-- can be easily reverted with: UPDATE songs SET artist = NULL, album = NULL WHERE artist LIKE '%_TEST';

WITH test_data AS (
  SELECT
    ROW_NUMBER() OVER () as rn,
    artist_name || '_TEST' as test_artist,
    album_name || '_TEST' as test_album
  FROM (
    VALUES
    ('aurora nights', 'midnight echoes'),
    ('velvet storms', 'electric dreams'),
    ('neon phantoms', 'synthetic hearts'),
    ('cosmic drifters', 'stellar wandering'),
    ('shadow collective', 'dark frequencies'),
    ('silver tongues', 'liquid mercury'),
    ('broken satellites', 'signal lost'),
    ('crimson waves', 'blood moon rising'),
    ('iron wolves', 'metal fangs'),
    ('glass rivers', 'crystal streams'),
    ('void dancers', 'empty spaces'),
    ('marble lions', 'stone guardians'),
    ('electric sheep', 'android dreams'),
    ('paper tigers', 'origami rebellion'),
    ('golden arrows', 'piercing light'),
    ('steel roses', 'thorned beauty'),
    ('phantom jazz', 'ghostly melodies'),
    ('urban decay', 'city ruins'),
    ('midnight oil', 'burning bright'),
    ('silver bullets', 'liquid ammunition'),
    ('red giants', 'stellar collapse'),
    ('blue notes', 'melancholy scales'),
    ('green light', 'go signals'),
    ('black holes', 'event horizon'),
    ('white noise', 'static interference'),
    ('grey matter', 'neural networks'),
    ('violet storms', 'purple lightning'),
    ('orange crush', 'citrus explosion'),
    ('yellow submarine', 'underwater voyage'),
    ('pink floyd tribute', 'brick walls'),
    ('chrome hearts', 'polished steel'),
    ('rust bucket', 'oxidized memories'),
    ('diamond dust', 'crystal fragments'),
    ('ruby laser', 'red beam'),
    ('emerald city', 'green metropolis'),
    ('sapphire sky', 'blue infinity'),
    ('pearl divers', 'ocean depths'),
    ('onyx shadow', 'black reflection'),
    ('jade temple', 'eastern wisdom'),
    ('amber waves', 'golden grain'),
    ('coral reef', 'underwater garden'),
    ('marble arch', 'stone monument'),
    ('bronze age', 'ancient metals'),
    ('platinum status', 'highest tier'),
    ('titanium strength', 'unbreakable bonds'),
    ('mercury rising', 'quicksilver ascent'),
    ('lead zeppelin', 'heavy flight'),
    ('copper wire', 'electrical connection'),
    ('aluminum foil', 'shiny wrapper'),
    ('zinc deficiency', 'mineral shortage'),
    ('carbon copy', 'exact duplicate'),
    ('silicon valley', 'tech paradise'),
    ('hydrogen bomb', 'nuclear fusion'),
    ('oxygen tank', 'life support'),
    ('nitrogen cycle', 'elemental loop'),
    ('phosphorus glow', 'chemical light'),
    ('sulfur springs', 'volcanic waters'),
    ('chlorine dreams', 'pool memories'),
    ('neon signs', 'bright advertisements'),
    ('argon gas', 'noble element'),
    ('helium balloons', 'floating celebration'),
    ('lithium battery', 'portable power'),
    ('sodium lights', 'street illumination'),
    ('magnesium flash', 'bright explosion'),
    ('calcium bones', 'skeletal structure'),
    ('potassium burst', 'sudden energy'),
    ('scandium rare', 'precious metal'),
    ('vanadium steel', 'alloy strength'),
    ('chromium shine', 'polished surface'),
    ('manganese nodules', 'ocean floor'),
    ('iron maiden', 'metal torture'),
    ('cobalt blue', 'vibrant pigment'),
    ('nickel back', 'canadian rock'),
    ('copper kettle', 'tea brewing'),
    ('zinc oxide', 'sun protection'),
    ('gallium liquid', 'room temperature metal'),
    ('germanium crystal', 'semiconductor base'),
    ('arsenic poison', 'deadly element'),
    ('selenium glow', 'photovoltaic cell'),
    ('bromine vapor', 'reddish gas'),
    ('krypton planet', 'superhero home'),
    ('rubidium clock', 'atomic time'),
    ('strontium fireworks', 'red flames'),
    ('yttrium lasers', 'infrared beams'),
    ('zirconium crown', 'dental implant'),
    ('niobium superconductor', 'zero resistance'),
    ('molybdenum steel', 'high strength'),
    ('technetium scan', 'medical imaging'),
    ('ruthenium catalyst', 'chemical reaction'),
    ('rhodium plating', 'precious coating'),
    ('palladium wedding', 'white metal ring'),
    ('silver screen', 'movie magic'),
    ('cadmium yellow', 'toxic pigment'),
    ('indium tin', 'transparent conductor'),
    ('antimony flame', 'fire retardant'),
    ('tellurium semiconductor', 'electrical component'),
    ('iodine solution', 'antiseptic treatment'),
    ('xenon headlights', 'bright illumination'),
    ('cesium clock', 'time standard'),
    ('barium meal', 'medical contrast'),
    ('lanthanum glass', 'optical element'),
    ('cerium lighter', 'spark generation'),
    ('praseodymium magnet', 'rare earth'),
    ('neodymium speakers', 'powerful magnets'),
    ('promethium glow', 'radioactive light'),
    ('samarium cobalt', 'permanent magnet'),
    ('europium phosphor', 'red emission'),
    ('gadolinium contrast', 'mri enhancement'),
    ('terbium green', 'fluorescent lamp'),
    ('dysprosium magnet', 'high temperature'),
    ('holmium laser', 'medical procedure'),
    ('erbium amplifier', 'optical fiber'),
    ('thulium laser', 'surgical tool'),
    ('ytterbium clock', 'precision timing'),
    ('lutetium pet', 'medical imaging'),
    ('hafnium control', 'nuclear reactor'),
    ('tantalum capacitor', 'electronic component'),
    ('tungsten filament', 'incandescent bulb'),
    ('rhenium catalyst', 'jet engine'),
    ('osmium density', 'heaviest metal'),
    ('iridium satellite', 'communication network'),
    ('platinum card', 'premium status'),
    ('gold rush', 'california dreams'),
    ('mercury vapor', 'street lighting'),
    ('thallium poison', 'murder mystery'),
    ('lead paint', 'toxic coating'),
    ('bismuth crystal', 'rainbow metal'),
    ('polonium source', 'radioactive element'),
    ('astatine rare', 'rarest element'),
    ('radon gas', 'basement hazard'),
    ('francium unstable', 'alkali metal'),
    ('radium glow', 'luminous paint'),
    ('actinium series', 'decay chain'),
    ('thorium reactor', 'nuclear fuel'),
    ('protactinium intermediate', 'uranium decay'),
    ('uranium fuel', 'nuclear power'),
    ('neptunium synthetic', 'transuranium element'),
    ('plutonium bomb', 'nuclear weapon'),
    ('americium smoke', 'detector source'),
    ('curium glow', 'radioactive light'),
    ('berkelium lab', 'synthetic element'),
    ('californium source', 'neutron generator'),
    ('einsteinium short', 'brief existence'),
    ('fermium heavy', 'synthetic element'),
    ('mendelevium artificial', 'lab creation'),
    ('nobelium unstable', 'radioactive decay'),
    ('lawrencium final', 'actinide series'),
    ('rutherfordium synthetic', 'super heavy'),
    ('dubnium artificial', 'lab element'),
    ('seaborgium unstable', 'brief life'),
    ('bohrium heavy', 'synthetic metal'),
    ('hassium rare', 'lab creation'),
    ('meitnerium brief', 'unstable element'),
    ('darmstadtium synthetic', 'heavy metal'),
    ('roentgenium artificial', 'lab element'),
    ('copernicium heavy', 'synthetic element'),
    ('nihonium artificial', 'japanese element'),
    ('flerovium synthetic', 'super heavy'),
    ('moscovium artificial', 'lab creation'),
    ('livermorium synthetic', 'heavy element'),
    ('tennessine artificial', 'halogen like'),
    ('oganesson noble', 'heaviest element'),
    ('quantum mechanics', 'probability waves'),
    ('string theory', 'vibrating dimensions'),
    ('dark matter', 'invisible mass'),
    ('black energy', 'cosmic expansion'),
    ('wormhole travel', 'spacetime shortcut'),
    ('parallel universe', 'alternate reality'),
    ('time machine', 'temporal transport'),
    ('gravity well', 'spacetime curve'),
    ('event horizon', 'point of no return'),
    ('singularity point', 'infinite density'),
    ('big bang', 'cosmic origin'),
    ('heat death', 'universal end'),
    ('entropy increase', 'disorder growth'),
    ('chaos theory', 'sensitive dependence'),
    ('butterfly effect', 'small changes'),
    ('strange attractor', 'chaotic pattern'),
    ('fractal geometry', 'self similar'),
    ('golden ratio', 'divine proportion'),
    ('fibonacci sequence', 'nature pattern'),
    ('prime numbers', 'indivisible integers'),
    ('complex analysis', 'imaginary numbers'),
    ('topology space', 'rubber sheet'),
    ('group theory', 'symmetry study'),
    ('number theory', 'integer properties'),
    ('game theory', 'strategic decisions'),
    ('information theory', 'data compression'),
    ('probability theory', 'random events'),
    ('statistics analysis', 'data interpretation'),
    ('regression models', 'predictive analysis'),
    ('neural networks', 'artificial intelligence'),
    ('machine learning', 'pattern recognition'),
    ('deep learning', 'layered networks'),
    ('computer vision', 'image processing'),
    ('natural language', 'text understanding'),
    ('speech recognition', 'voice processing'),
    ('robotic control', 'automated movement'),
    ('autonomous vehicles', 'self driving'),
    ('blockchain technology', 'distributed ledger'),
    ('cryptocurrency mining', 'digital currency'),
    ('virtual reality', 'immersive experience'),
    ('augmented reality', 'enhanced perception'),
    ('mixed reality', 'blended worlds'),
    ('holographic display', 'three dimensional'),
    ('quantum computing', 'superposition states'),
    ('edge computing', 'distributed processing'),
    ('cloud storage', 'remote data'),
    ('internet of things', 'connected devices'),
    ('smart contracts', 'automated agreements'),
    ('digital twins', 'virtual replicas'),
    ('cybersecurity threats', 'digital protection'),
    ('data privacy', 'information security'),
    ('artificial general', 'human level ai'),
    ('superintelligence', 'beyond human'),
    ('technological singularity', 'ai explosion'),
    ('transhumanism', 'human enhancement'),
    ('life extension', 'longevity research'),
    ('genetic engineering', 'dna modification'),
    ('synthetic biology', 'engineered life'),
    ('nanotechnology', 'molecular machines'),
    ('space exploration', 'cosmic journey'),
    ('mars colonization', 'red planet'),
    ('asteroid mining', 'space resources'),
    ('solar power', 'renewable energy'),
    ('fusion reactors', 'clean nuclear'),
    ('climate change', 'global warming')
  ) AS artists_albums(artist_name, album_name)
),
songs_with_nulls AS (
  SELECT id, ROW_NUMBER() OVER (ORDER BY id) as song_rn
  FROM songs
  WHERE artist IS NULL OR album IS NULL
),
assignments AS (
  SELECT
    swn.id,
    td.test_artist,
    td.test_album
  FROM songs_with_nulls swn
  JOIN test_data td ON ((swn.song_rn - 1) % 200) + 1 = td.rn
)
UPDATE songs
SET
  artist = assignments.test_artist,
  album = assignments.test_album
FROM assignments
WHERE songs.id = assignments.id;

-- show results
SELECT
  COUNT(*) as updated_songs,
  COUNT(DISTINCT artist) as distinct_artists,
  COUNT(DISTINCT album) as distinct_albums
FROM songs
WHERE artist LIKE '%_TEST';
