// Re-export all types from schemas for convenient importing
export type {
  Song,
  SongListResponse,
  PlaylistSong,
  QueueItem,
  ArtistSummary,
  ArtistsListResponse,
  ArtistSongsResponse,
  Album,
  AlbumListResponse,
  AlbumTracksResponse,
  Playlist,
  PlaylistListResponse,
  PlaylistSongsResponse,
  CreatePlaylistRequest,
  UpdatePlaylistRequest,
  AddSongsToPlaylistRequest,
  RemoveSongsFromPlaylistRequest,
  UpdateSongRequest,
  SongUpdateResponse,
  MoveSongRequest,
  ReorderPlaylistRequest,
  CreatePlaylistFromAlbumRequest,
  PlaylistSummaryResponse,
} from "./schemas/index.js";
