// Automatically generated by zod_gen
import * as z from 'zod';

export const AddSongsToPlaylistRequestSchema = z.object({
  playlist_id: z.string(),
  songs: z.array(z.object({
  song_id: z.string(),
  position: z.number(),
  added_by: z.string(),
  added_at: z.number()
})),
  replace_existing: z.boolean()
});
export type AddSongsToPlaylistRequest = z.infer<typeof AddSongsToPlaylistRequestSchema>;

export const AlbumSchema = z.object({
  id: z.string(),
  title: z.string(),
  artist_name: z.string(),
  year: z.number().nullable()
});
export type Album = z.infer<typeof AlbumSchema>;

export const CreateUserRequestSchema = z.object({
  username: z.string(),
  password: z.string(),
  email: z.string().nullable()
});
export type CreateUserRequest = z.infer<typeof CreateUserRequestSchema>;

export const LoginRequestSchema = z.object({
  username: z.string(),
  password: z.string()
});
export type LoginRequest = z.infer<typeof LoginRequestSchema>;

export const LoginResponseSchema = z.object({
  user: z.object({
  id: z.string(),
  username: z.string(),
  email: z.string().nullable(),
  created_at: z.number()
}),
  api_key: z.string()
});
export type LoginResponse = z.infer<typeof LoginResponseSchema>;

export const PlaylistSchema = z.object({
  id: z.string(),
  title: z.string(),
  description: z.string().nullable()
});
export type Playlist = z.infer<typeof PlaylistSchema>;

export const PlaylistQueryResultSchema = z.object({
  playlist: z.object({
  id: z.string(),
  title: z.string(),
  description: z.string().nullable()
}),
  song_count: z.number()
});
export type PlaylistQueryResult = z.infer<typeof PlaylistQueryResultSchema>;

export const PlaylistUpdateResultSchema = z.object({
  playlist_id: z.string(),
  total_songs: z.number(),
  songs_added: z.number(),
  songs_skipped: z.number(),
  updated_at: z.number()
});
export type PlaylistUpdateResult = z.infer<typeof PlaylistUpdateResultSchema>;

export const QueryParamsSchema = z.object({
  q: z.string().nullable(),
  limit: z.number().nullable(),
  offset: z.number().nullable()
});
export type QueryParams = z.infer<typeof QueryParamsSchema>;

export const SongSchema = z.object({
  id: z.string(),
  title: z.string(),
  artist_name: z.string()
});
export type Song = z.infer<typeof SongSchema>;

export const SongPositionSchema = z.object({
  song_id: z.string(),
  position: z.number(),
  added_by: z.string(),
  added_at: z.number()
});
export type SongPosition = z.infer<typeof SongPositionSchema>;

export const UserSchema = z.object({
  id: z.string(),
  username: z.string(),
  email: z.string().nullable(),
  created_at: z.number()
});
export type User = z.infer<typeof UserSchema>;

